{- HLINT ignore "Use camelCase" -}

-- | Embedding of the WebAssembly Text Format (WAT) from the WebAssembly Specification Release 3.0 (2026-07-07).
module Language.Wasm.Wat where

import Data.ByteString (ByteString)
import Data.List (singleton)
import Data.Text (Text)
import Data.Text qualified as Text
import GHC.Generics (Generic)
import Numeric.Natural (Natural)
import Prettyprinter
import Prettyprinter.Util (reflow)

--------------------------------

data Sexp = Node Text [Sexp]
  deriving (Generic, Eq, Show, Ord)

pattern Leaf :: Text -> Sexp
pattern Leaf t = Node t []

instance Pretty Sexp where
  pretty (Leaf t) = reflow t
  pretty (Node t es) = parens $ reflow t <+> (hcat . punctuate " " . fmap pretty) es

class EncodeWatSexp a where
  encodeWatSexp :: a -> Sexp

class EncodeWatSexpList a where
  encodeWatSexpList :: a -> [Sexp]

instance (EncodeWatSexp a) => EncodeWatSexpList (Maybe a) where
  encodeWatSexpList = foldMap (singleton . encodeWatSexp)

--------------------------------

-- # 6 WebAssembly Text Format (WAT)

-- ## 6.3 Values

-- ### 6.3.1 Integers

-- Use Haskell's `Integer`

-- ### 6.3.2 Floating Point

-- Use Haskell's `Float`

-- ### 6.3.3 Strings

-- Use Haskell's `ByteString`

-- ### 6.3.4 Names

-- | Names are strings denoting a literal character sequence.
data Name = Name Text
  deriving (Generic, Eq, Show, Ord)

-- ### 6.3.5 Identifiers

-- | Indices can be given in both numeric and symbolic form. Symbolic identifiers that stand in lieu of indices start with "$".
data Identifier = Identifier Text
  deriving (Generic, Eq, Show, Ord)

-- ## 6.4 Types

-- ### 6.4.1 Number Types

data NumType
  = I32_NumType
  | I64_NumType
  | F32_NumType
  | F64_NumType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.2 Vector Types

data VecType
  = V128_VecType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.3 Heap Types

data AbsHeapType
  = Any_AbsHeapType
  | Eq_AbsHeapType
  | I31_AbsHeapType
  | Struct_AbsHeapType
  | Array_AbsHeapType
  | None_AbsHeapType
  | Func_AbsHeapType
  | NoFunc_AbsHeapType
  | Exn_AbsHeapType
  | NoExn_AbsHeapType
  | Extern_AbsHeapType
  | NoExtern_AbsHeapType
  deriving (Generic, Eq, Show, Ord)

data HeapType
  = AbsHeapType_HeapType AbsHeapType
  | TypeIdx_HeapType TypeIdx
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.4 Reference Types

data Null = Null
  deriving (Generic, Eq, Show, Ord)

data RefType = RefType (Maybe Null) HeapType
  deriving (Generic, Eq, Show, Ord)

anyRefType :: RefType
anyRefType = RefType (Just Null) (AbsHeapType_HeapType Any_AbsHeapType)

eqRefType :: RefType
eqRefType = RefType (Just Null) (AbsHeapType_HeapType Eq_AbsHeapType)

i31RefType :: RefType
i31RefType = RefType (Just Null) (AbsHeapType_HeapType I31_AbsHeapType)

structRefType :: RefType
structRefType = RefType (Just Null) (AbsHeapType_HeapType Struct_AbsHeapType)

arrayRefType :: RefType
arrayRefType = RefType (Just Null) (AbsHeapType_HeapType Array_AbsHeapType)

noneRefType :: RefType
noneRefType = RefType (Just Null) (AbsHeapType_HeapType None_AbsHeapType)

funcRefType :: RefType
funcRefType = RefType (Just Null) (AbsHeapType_HeapType Func_AbsHeapType)

noFuncRefType :: RefType
noFuncRefType = RefType (Just Null) (AbsHeapType_HeapType NoFunc_AbsHeapType)

exnRefType :: RefType
exnRefType = RefType (Just Null) (AbsHeapType_HeapType Exn_AbsHeapType)

noExnRefType :: RefType
noExnRefType = RefType (Just Null) (AbsHeapType_HeapType NoExn_AbsHeapType)

externRefType :: RefType
externRefType = RefType (Just Null) (AbsHeapType_HeapType Extern_AbsHeapType)

noExternRefType :: RefType
noExternRefType = RefType (Just Null) (AbsHeapType_HeapType NoExtern_AbsHeapType)

-- ### 6.4.5 Value Types

data ValType
  = NumType_ValType NumType
  | VecType_ValType VecType
  | RefType_ValType RefType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.6 Composite Types

-- | Composite types are parsed into their respective abstract representation, paired with the local identifier context generated by their bound field or parameter identifiers.
data CompType
  = Struct_CompType [Field]
  | Array_CompType FieldType
  | Func_CompType [Param] [Result]
  deriving (Generic, Eq, Show, Ord)

-- | A field declaration with an optional identifier and field type.
data Field = Field (Maybe Identifier) FieldType
  deriving (Generic, Eq, Show, Ord)

-- | A parameter declaration with an optional identifier and value type.
data Param = Param (Maybe Identifier) ValType
  deriving (Generic, Eq, Show, Ord)

-- | A result declaration specifying a value type.
newtype Result = Result ValType
  deriving (Generic, Eq, Show, Ord)

-- | Field types can be mutable or immutable.
data FieldType = FieldType Bool StorageType
  deriving (Generic, Eq, Show, Ord)

-- | Storage types represent either value types or packed types.
data StorageType
  = ValType_StorageType ValType
  | PackType_StorageType PackType
  deriving (Generic, Eq, Show, Ord)

-- | Pack types represent i8 or i16 types.
data PackType
  = I8_PackType
  | I16_PackType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.7 Recursive Types

-- | Final types represent completed types.
data Final = Final
  deriving (Generic, Eq, Show, Ord)

-- | Sub types specify inheritance relationships and composite types.
data SubType = SubType (Maybe Final) [TypeIdx] CompType
  deriving (Generic, Eq, Show, Ord)

-- | Type definitions declare custom types with optional identifiers.
data TypeDef = TypeDef (Maybe Identifier) SubType
  deriving (Generic, Eq, Show, Ord)

-- | Recursive types are parsed into their respective abstract representation.
data RecType = RecType [TypeDef]
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.8 Address Types

-- | Address types are either i32 or i64.
data AddrType
  = I32_AddrType
  | I64_AddrType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.9 Limits

-- | Limits specify initial and optional maximum sizes.
data Limits = Limits Natural (Maybe Natural)
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.10 Tag Types

-- | Tag types specify the type signature of exception or event tags.
newtype TagType = TagType TypeUse
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.11 Global Types

-- | Global types specify the value type and mutability of a global variable.
data GlobalType = GlobalType Bool ValType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.12 Memory Types

-- | Memory types specify address types and size limits.
data MemType = MemType (Maybe AddrType) Limits
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.13 Table Types

-- | Table types specify address types, limits, and reference types.
data TableType = TableType (Maybe AddrType) Limits RefType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.14 External Types

-- | External types classify the kind of imports and exports.
data ExternalType
  = Tag_ExternalType (Maybe Identifier) TagType
  | Global_ExternalType (Maybe Identifier) GlobalType
  | Memory_ExternalType (Maybe Identifier) MemType
  | Table_ExternalType (Maybe Identifier) TableType
  | Func_ExternalType (Maybe Identifier) TypeUse
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.15 Type Uses

-- | Type uses reference type definitions, optionally inlining parameter and result declarations.
data TypeUse = TypeUse TypeIdx
  deriving (Generic, Eq, Show, Ord)

-- ## 6.5 Instructions

-- ### 6.5.1 Labels

-- | Structured control instructions can be annotated with an optional symbolic label identifier.
newtype Label = Label (Maybe Identifier)
  deriving (Generic, Eq, Show, Ord)

-- ### 6.5.2 to 6.5.10 Instructions

-- | Block types are either result types or references to type definitions.
data BlockType
  = Result_BlockType (Maybe Result)
  | TypeUse_BlockType TypeUse
  deriving (Generic, Eq, Show, Ord)

-- | Structured catch clauses for exception handling.
data Catch
  = Catch TagIdx LabelIdx
  | CatchRef TagIdx LabelIdx
  | CatchAll LabelIdx
  | CatchAllRef LabelIdx
  deriving (Generic, Eq, Show, Ord)

-- | Structured control instructions.
data BlockInstr
  = Block_BlockInstr (Maybe Identifier) BlockType [Instr] (Maybe Identifier)
  | Loop_BlockInstr (Maybe Identifier) BlockType [Instr] (Maybe Identifier)
  | If_BlockInstr (Maybe Identifier) BlockType [Instr] (Maybe Identifier) [Instr] (Maybe Identifier)
  | TryTable_BlockInstr (Maybe Identifier) BlockType [Catch] [Instr] (Maybe Identifier)
  deriving (Generic, Eq, Show, Ord)

-- | Memory instruction arguments (offset and alignment).
data MemArg = MemArg (Maybe Natural) (Maybe Natural)
  deriving (Generic, Eq, Show, Ord)

isMemArgEmpty :: MemArg -> Bool
isMemArgEmpty (MemArg Nothing Nothing) = True
isMemArgEmpty _ = False

-- | Lane index for SIMD instructions.
newtype LaneIdx = LaneIdx Natural
  deriving (Generic, Eq, Show, Ord)

-- | Plain instruction forms of WebAssembly.
data PlainInstr
  = -- ### 6.5.2 Parametric Instructions
    Unreachable_PlainInstr
  | Nop_PlainInstr
  | Drop_PlainInstr
  | Select_PlainInstr (Maybe [Result])
  | -- ### 6.5.3 Plain Control Instructions
    Br_PlainInstr LabelIdx
  | BrIf_PlainInstr LabelIdx
  | BrTable_PlainInstr [LabelIdx] LabelIdx
  | Return_PlainInstr
  | Call_PlainInstr FuncIdx
  | ReturnCall_PlainInstr FuncIdx
  | CallIndirect_PlainInstr TableIdx TypeUse
  | ReturnCallIndirect_PlainInstr TableIdx TypeUse
  | -- ### 6.5.4 Variable Instructions
    LocalGet_PlainInstr LocalIdx
  | LocalSet_PlainInstr LocalIdx
  | LocalTee_PlainInstr LocalIdx
  | GlobalGet_PlainInstr GlobalIdx
  | GlobalSet_PlainInstr GlobalIdx
  | -- ### 6.5.5 Table Instructions
    TableGet_PlainInstr TableIdx
  | TableSet_PlainInstr TableIdx
  | TableSize_PlainInstr TableIdx
  | TableGrow_PlainInstr TableIdx
  | TableFill_PlainInstr TableIdx
  | TableCopy_PlainInstr TableIdx TableIdx
  | TableInit_PlainInstr TableIdx ElemIdx
  | ElemDrop_PlainInstr ElemIdx
  | -- ### 6.5.6 Memory Instructions
    I32Load_PlainInstr MemIdx MemArg
  | I64Load_PlainInstr MemIdx MemArg
  | F32Load_PlainInstr MemIdx MemArg
  | F64Load_PlainInstr MemIdx MemArg
  | I32Load8S_PlainInstr MemIdx MemArg
  | I32Load8U_PlainInstr MemIdx MemArg
  | I32Load16S_PlainInstr MemIdx MemArg
  | I32Load16U_PlainInstr MemIdx MemArg
  | I64Load8S_PlainInstr MemIdx MemArg
  | I64Load8U_PlainInstr MemIdx MemArg
  | I64Load16S_PlainInstr MemIdx MemArg
  | I64Load16U_PlainInstr MemIdx MemArg
  | I64Load32S_PlainInstr MemIdx MemArg
  | I64Load32U_PlainInstr MemIdx MemArg
  | V128Load_PlainInstr MemIdx MemArg
  | V128Load8x8S_PlainInstr MemIdx MemArg
  | V128Load8x8U_PlainInstr MemIdx MemArg
  | V128Load16x4S_PlainInstr MemIdx MemArg
  | V128Load16x4U_PlainInstr MemIdx MemArg
  | V128Load32x2S_PlainInstr MemIdx MemArg
  | V128Load32x2U_PlainInstr MemIdx MemArg
  | V128Load8Splat_PlainInstr MemIdx MemArg
  | V128Load16Splat_PlainInstr MemIdx MemArg
  | V128Load32Splat_PlainInstr MemIdx MemArg
  | V128Load64Splat_PlainInstr MemIdx MemArg
  | V128Load32Zero_PlainInstr MemIdx MemArg
  | V128Load64Zero_PlainInstr MemIdx MemArg
  | V128Load8Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Load16Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Load32Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Load64Lane_PlainInstr MemIdx MemArg LaneIdx
  | I32Store_PlainInstr MemIdx MemArg
  | I64Store_PlainInstr MemIdx MemArg
  | F32Store_PlainInstr MemIdx MemArg
  | F64Store_PlainInstr MemIdx MemArg
  | I32Store8_PlainInstr MemIdx MemArg
  | I32Store16_PlainInstr MemIdx MemArg
  | I64Store8_PlainInstr MemIdx MemArg
  | I64Store16_PlainInstr MemIdx MemArg
  | I64Store32_PlainInstr MemIdx MemArg
  | V128Store_PlainInstr MemIdx MemArg
  | V128Store8Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Store16Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Store32Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Store64Lane_PlainInstr MemIdx MemArg LaneIdx
  | MemorySize_PlainInstr MemIdx
  | MemoryGrow_PlainInstr MemIdx
  | MemoryFill_PlainInstr MemIdx
  | MemoryCopy_PlainInstr MemIdx MemIdx
  | MemoryInit_PlainInstr MemIdx DataIdx
  | DataDrop_PlainInstr DataIdx
  | -- ### 6.5.7 Reference Instructions
    RefNull_PlainInstr HeapType
  | RefFunc_PlainInstr FuncIdx
  | RefIsNull_PlainInstr
  | RefAsNonNull_PlainInstr
  | RefEq_PlainInstr
  | RefTest_PlainInstr RefType
  | RefCast_PlainInstr RefType
  | -- ### 6.5.8 Aggregate Instructions
    RefI31_PlainInstr
  | I31GetS_PlainInstr
  | I31GetU_PlainInstr
  | StructNew_PlainInstr TypeIdx
  | StructNewDefault_PlainInstr TypeIdx
  | StructGet_PlainInstr TypeIdx FieldIdx
  | StructGetS_PlainInstr TypeIdx FieldIdx
  | StructGetU_PlainInstr TypeIdx FieldIdx
  | StructSet_PlainInstr TypeIdx FieldIdx
  | ArrayNew_PlainInstr TypeIdx
  | ArrayNewDefault_PlainInstr TypeIdx
  | ArrayNewFixed_PlainInstr TypeIdx Natural
  | ArrayNewData_PlainInstr TypeIdx DataIdx
  | ArrayNewElem_PlainInstr TypeIdx ElemIdx
  | ArrayGet_PlainInstr TypeIdx
  | ArrayGetS_PlainInstr TypeIdx
  | ArrayGetU_PlainInstr TypeIdx
  | ArraySet_PlainInstr TypeIdx
  | ArrayLen_PlainInstr
  | ArrayFill_PlainInstr TypeIdx
  | ArrayCopy_PlainInstr TypeIdx TypeIdx
  | ArrayInitData_PlainInstr TypeIdx DataIdx
  | ArrayInitElem_PlainInstr TypeIdx ElemIdx
  | AnyConvertExtern_PlainInstr
  | ExternConvertAny_PlainInstr
  | -- ### 6.5.9 Numeric Const Instructions
    I32Const_PlainInstr Integer
  | I64Const_PlainInstr Integer
  | F32Const_PlainInstr Float
  | F64Const_PlainInstr Float
  | -- ### 6.5.9 Numeric Operators
    -- i32 operators
    I32Eqz_PlainInstr
  | I32Eq_PlainInstr
  | I32Ne_PlainInstr
  | I32LtS_PlainInstr
  | I32LtU_PlainInstr
  | I32GtS_PlainInstr
  | I32GtU_PlainInstr
  | I32LeS_PlainInstr
  | I32LeU_PlainInstr
  | I32GeS_PlainInstr
  | I32GeU_PlainInstr
  | I32Clz_PlainInstr
  | I32Ctz_PlainInstr
  | I32Popcnt_PlainInstr
  | I32Extend8S_PlainInstr
  | I32Extend16S_PlainInstr
  | I32Add_PlainInstr
  | I32Sub_PlainInstr
  | I32Mul_PlainInstr
  | I32DivS_PlainInstr
  | I32DivU_PlainInstr
  | I32RemS_PlainInstr
  | I32RemU_PlainInstr
  | I32And_PlainInstr
  | I32Or_PlainInstr
  | I32Xor_PlainInstr
  | I32Shl_PlainInstr
  | I32ShrS_PlainInstr
  | I32ShrU_PlainInstr
  | I32Rotl_PlainInstr
  | I32Rotr_PlainInstr
  | -- i64 operators
    I64Eqz_PlainInstr
  | I64Eq_PlainInstr
  | I64Ne_PlainInstr
  | I64LtS_PlainInstr
  | I64LtU_PlainInstr
  | I64GtS_PlainInstr
  | I64GtU_PlainInstr
  | I64LeS_PlainInstr
  | I64LeU_PlainInstr
  | I64GeS_PlainInstr
  | I64GeU_PlainInstr
  | I64Clz_PlainInstr
  | I64Ctz_PlainInstr
  | I64Popcnt_PlainInstr
  | I64Extend8S_PlainInstr
  | I64Extend16S_PlainInstr
  | I64Extend32S_PlainInstr
  | I64Add_PlainInstr
  | I64Sub_PlainInstr
  | I64Mul_PlainInstr
  | I64DivS_PlainInstr
  | I64DivU_PlainInstr
  | I64RemS_PlainInstr
  | I64RemU_PlainInstr
  | I64And_PlainInstr
  | I64Or_PlainInstr
  | I64Xor_PlainInstr
  | I64Shl_PlainInstr
  | I64ShrS_PlainInstr
  | I64ShrU_PlainInstr
  | I64Rotl_PlainInstr
  | I64Rotr_PlainInstr
  | -- f32 operators
    F32Eq_PlainInstr
  | F32Ne_PlainInstr
  | F32Lt_PlainInstr
  | F32Gt_PlainInstr
  | F32Le_PlainInstr
  | F32Ge_PlainInstr
  | F32Abs_PlainInstr
  | F32Neg_PlainInstr
  | F32Sqrt_PlainInstr
  | F32Ceil_PlainInstr
  | F32Floor_PlainInstr
  | F32Trunc_PlainInstr
  | F32Nearest_PlainInstr
  | F32Add_PlainInstr
  | F32Sub_PlainInstr
  | F32Mul_PlainInstr
  | F32Div_PlainInstr
  | F32Min_PlainInstr
  | F32Max_PlainInstr
  | F32Copysign_PlainInstr
  | -- f64 operators
    F64Eq_PlainInstr
  | F64Ne_PlainInstr
  | F64Lt_PlainInstr
  | F64Gt_PlainInstr
  | F64Le_PlainInstr
  | F64Ge_PlainInstr
  | F64Abs_PlainInstr
  | F64Neg_PlainInstr
  | F64Sqrt_PlainInstr
  | F64Ceil_PlainInstr
  | F64Floor_PlainInstr
  | F64Trunc_PlainInstr
  | F64Nearest_PlainInstr
  | F64Add_PlainInstr
  | F64Sub_PlainInstr
  | F64Mul_PlainInstr
  | F64Div_PlainInstr
  | F64Min_PlainInstr
  | F64Max_PlainInstr
  | F64Copysign_PlainInstr
  | -- conversions
    I32WrapI64_PlainInstr
  | I32TruncF32S_PlainInstr
  | I32TruncF32U_PlainInstr
  | I32TruncF64S_PlainInstr
  | I32TruncF64U_PlainInstr
  | I32TruncSatF32S_PlainInstr
  | I32TruncSatF32U_PlainInstr
  | I32TruncSatF64S_PlainInstr
  | I32TruncSatF64U_PlainInstr
  | I64ExtendI32S_PlainInstr
  | I64ExtendI32U_PlainInstr
  | I64TruncF32S_PlainInstr
  | I64TruncF32U_PlainInstr
  | I64TruncF64S_PlainInstr
  | I64TruncF64U_PlainInstr
  | I64TruncSatF32S_PlainInstr
  | I64TruncSatF32U_PlainInstr
  | I64TruncSatF64S_PlainInstr
  | I64TruncSatF64U_PlainInstr
  | F32DemoteF64_PlainInstr
  | F32ConvertI32S_PlainInstr
  | F32ConvertI32U_PlainInstr
  | F32ConvertI64S_PlainInstr
  | F32ConvertI64U_PlainInstr
  | F64PromoteF32_PlainInstr
  | F64ConvertI32S_PlainInstr
  | F64ConvertI32U_PlainInstr
  | F64ConvertI64S_PlainInstr
  | F64ConvertI64U_PlainInstr
  | I32ReinterpretF32_PlainInstr
  | I64ReinterpretF64_PlainInstr
  | F32ReinterpretI32_PlainInstr
  | F64ReinterpretI64_PlainInstr
  | -- ### 6.5.10 Vector Instructions
    -- vector const and shuffle
    V128Const_PlainInstr Text [Integer]
  | I8x16Shuffle_PlainInstr [LaneIdx]
  | -- swizzle and splats
    I8x16Swizzle_PlainInstr
  | I8x16RelaxedSwizzle_PlainInstr
  | I8x16Splat_PlainInstr
  | I16x8Splat_PlainInstr
  | I32x4Splat_PlainInstr
  | I64x2Splat_PlainInstr
  | F32x4Splat_PlainInstr
  | F64x2Splat_PlainInstr
  | -- lanes
    I8x16ExtractLaneS_PlainInstr LaneIdx
  | I8x16ExtractLaneU_PlainInstr LaneIdx
  | I16x8ExtractLaneS_PlainInstr LaneIdx
  | I16x8ExtractLaneU_PlainInstr LaneIdx
  | I32x4ExtractLane_PlainInstr LaneIdx
  | I64x2ExtractLane_PlainInstr LaneIdx
  | F32x4ExtractLane_PlainInstr LaneIdx
  | F64x2ExtractLane_PlainInstr LaneIdx
  | I8x16ReplaceLane_PlainInstr LaneIdx
  | I16x8ReplaceLane_PlainInstr LaneIdx
  | I32x4ReplaceLane_PlainInstr LaneIdx
  | I64x2ReplaceLane_PlainInstr LaneIdx
  | F32x4ReplaceLane_PlainInstr LaneIdx
  | F64x2ReplaceLane_PlainInstr LaneIdx
  | -- vector ops
    V128AnyTrue_PlainInstr
  | V128Not_PlainInstr
  | V128And_PlainInstr
  | V128Andnot_PlainInstr
  | V128Or_PlainInstr
  | V128Xor_PlainInstr
  | V128Bitselect_PlainInstr
  | I8x16AllTrue_PlainInstr
  | I8x16Eq_PlainInstr
  | I8x16Ne_PlainInstr
  | I8x16LtS_PlainInstr
  | I8x16LtU_PlainInstr
  | I8x16GtS_PlainInstr
  | I8x16GtU_PlainInstr
  | I8x16LeS_PlainInstr
  | I8x16LeU_PlainInstr
  | I8x16GeS_PlainInstr
  | I8x16GeU_PlainInstr
  | I8x16Abs_PlainInstr
  | I8x16Neg_PlainInstr
  | I8x16Popcnt_PlainInstr
  | I8x16Add_PlainInstr
  | I8x16AddSatS_PlainInstr
  | I8x16AddSatU_PlainInstr
  | I8x16Sub_PlainInstr
  | I8x16SubSatS_PlainInstr
  | I8x16SubSatU_PlainInstr
  | I8x16MinS_PlainInstr
  | I8x16MinU_PlainInstr
  | I8x16MaxS_PlainInstr
  | I8x16MaxU_PlainInstr
  | I8x16AvgrU_PlainInstr
  | I8x16RelaxedLaneselect_PlainInstr
  | I8x16Shl_PlainInstr
  | I8x16ShrS_PlainInstr
  | I8x16ShrU_PlainInstr
  | I8x16Bitmask_PlainInstr
  | I8x16NarrowI16x8S_PlainInstr
  | I8x16NarrowI16x8U_PlainInstr
  | -- i16x8 ops
    I16x8AllTrue_PlainInstr
  | I16x8Eq_PlainInstr
  | I16x8Ne_PlainInstr
  | I16x8LtS_PlainInstr
  | I16x8LtU_PlainInstr
  | I16x8GtS_PlainInstr
  | I16x8GtU_PlainInstr
  | I16x8LeS_PlainInstr
  | I16x8LeU_PlainInstr
  | I16x8GeS_PlainInstr
  | I16x8GeU_PlainInstr
  | I16x8Abs_PlainInstr
  | I16x8Neg_PlainInstr
  | I16x8Add_PlainInstr
  | I16x8AddSatS_PlainInstr
  | I16x8AddSatU_PlainInstr
  | I16x8Sub_PlainInstr
  | I16x8SubSatS_PlainInstr
  | I16x8SubSatU_PlainInstr
  | I16x8Mul_PlainInstr
  | I16x8MinS_PlainInstr
  | I16x8MinU_PlainInstr
  | I16x8MaxS_PlainInstr
  | I16x8MaxU_PlainInstr
  | I16x8AvgrU_PlainInstr
  | I16x8Q15mulrSatS_PlainInstr
  | I16x8RelaxedQ15mulrS_PlainInstr
  | I16x8RelaxedLaneselect_PlainInstr
  | I16x8Shl_PlainInstr
  | I16x8ShrS_PlainInstr
  | I16x8ShrU_PlainInstr
  | I16x8Bitmask_PlainInstr
  | I16x8NarrowI32x4S_PlainInstr
  | I16x8NarrowI32x4U_PlainInstr
  | -- i32x4 ops
    I32x4AllTrue_PlainInstr
  | I32x4Eq_PlainInstr
  | I32x4Ne_PlainInstr
  | I32x4LtS_PlainInstr
  | I32x4LtU_PlainInstr
  | I32x4GtS_PlainInstr
  | I32x4GtU_PlainInstr
  | I32x4LeS_PlainInstr
  | I32x4LeU_PlainInstr
  | I32x4GeS_PlainInstr
  | I32x4GeU_PlainInstr
  | I32x4Abs_PlainInstr
  | I32x4Neg_PlainInstr
  | I32x4Add_PlainInstr
  | I32x4Sub_PlainInstr
  | I32x4Mul_PlainInstr
  | I32x4MinS_PlainInstr
  | I32x4MinU_PlainInstr
  | I32x4MaxS_PlainInstr
  | I32x4MaxU_PlainInstr
  | I32x4RelaxedLaneselect_PlainInstr
  | I32x4Shl_PlainInstr
  | I32x4ShrS_PlainInstr
  | I32x4ShrU_PlainInstr
  | I32x4Bitmask_PlainInstr
  | -- i64x2 ops
    I64x2AllTrue_PlainInstr
  | I64x2Eq_PlainInstr
  | I64x2Ne_PlainInstr
  | I64x2LtS_PlainInstr
  | I64x2GtS_PlainInstr
  | I64x2LeS_PlainInstr
  | I64x2GeS_PlainInstr
  | I64x2Abs_PlainInstr
  | I64x2Neg_PlainInstr
  | I64x2Add_PlainInstr
  | I64x2Sub_PlainInstr
  | I64x2Mul_PlainInstr
  | I64x2RelaxedLaneselect_PlainInstr
  | I64x2Shl_PlainInstr
  | I64x2ShrS_PlainInstr
  | I64x2ShrU_PlainInstr
  | I64x2Bitmask_PlainInstr
  | -- f32x4 ops
    F32x4Eq_PlainInstr
  | F32x4Ne_PlainInstr
  | F32x4Lt_PlainInstr
  | F32x4Gt_PlainInstr
  | F32x4Le_PlainInstr
  | F32x4Ge_PlainInstr
  | F32x4Abs_PlainInstr
  | F32x4Neg_PlainInstr
  | F32x4Sqrt_PlainInstr
  | F32x4Ceil_PlainInstr
  | F32x4Floor_PlainInstr
  | F32x4Trunc_PlainInstr
  | F32x4Nearest_PlainInstr
  | F32x4Add_PlainInstr
  | F32x4Sub_PlainInstr
  | F32x4Mul_PlainInstr
  | F32x4Div_PlainInstr
  | F32x4Min_PlainInstr
  | F32x4Max_PlainInstr
  | F32x4Pmin_PlainInstr
  | F32x4Pmax_PlainInstr
  | F32x4RelaxedMin_PlainInstr
  | F32x4RelaxedMax_PlainInstr
  | F32x4RelaxedMadd_PlainInstr
  | F32x4RelaxedNmadd_PlainInstr
  | -- f64x2 ops
    F64x2Eq_PlainInstr
  | F64x2Ne_PlainInstr
  | F64x2Lt_PlainInstr
  | F64x2Gt_PlainInstr
  | F64x2Le_PlainInstr
  | F64x2Ge_PlainInstr
  | F64x2Abs_PlainInstr
  | F64x2Neg_PlainInstr
  | F64x2Sqrt_PlainInstr
  | F64x2Ceil_PlainInstr
  | F64x2Floor_PlainInstr
  | F64x2Trunc_PlainInstr
  | F64x2Nearest_PlainInstr
  | F64x2Add_PlainInstr
  | F64x2Sub_PlainInstr
  | F64x2Mul_PlainInstr
  | F64x2Div_PlainInstr
  | F64x2Min_PlainInstr
  | F64x2Max_PlainInstr
  | F64x2Pmin_PlainInstr
  | F64x2Pmax_PlainInstr
  | F64x2RelaxedMin_PlainInstr
  | F64x2RelaxedMax_PlainInstr
  | F64x2RelaxedMadd_PlainInstr
  | F64x2RelaxedNmadd_PlainInstr
  | -- extension vectors (page 26)
    I16x8ExtendLowI8x16S_PlainInstr
  | I16x8ExtendLowI8x16U_PlainInstr
  | I16x8ExtendHighI8x16S_PlainInstr
  | I16x8ExtendHighI8x16U_PlainInstr
  | I32x4ExtendLowI16x8S_PlainInstr
  | I32x4ExtendLowI16x8U_PlainInstr
  | I32x4ExtendHighI16x8S_PlainInstr
  | I32x4ExtendHighI16x8U_PlainInstr
  | I32x4TruncSatF32x4S_PlainInstr
  | I32x4TruncSatF32x4U_PlainInstr
  | I32x4TruncSatF64x2SZero_PlainInstr
  | I32x4TruncSatF64x2UZero_PlainInstr
  | I32x4RelaxedTruncF32x4S_PlainInstr
  | I32x4RelaxedTruncF32x4U_PlainInstr
  | I32x4RelaxedTruncF64x2SZero_PlainInstr
  | I32x4RelaxedTruncF64x2UZero_PlainInstr
  | I64x2ExtendLowI32x4S_PlainInstr
  | I64x2ExtendLowI32x4U_PlainInstr
  | I64x2ExtendHighI32x4S_PlainInstr
  | I64x2ExtendHighI32x4U_PlainInstr
  | F32x4DemoteF64x2Zero_PlainInstr
  | F32x4ConvertI32x4S_PlainInstr
  | F32x4ConvertI32x4U_PlainInstr
  | F64x2PromoteLowF32x4_PlainInstr
  | F64x2ConvertLowI32x4S_PlainInstr
  | F64x2ConvertLowI32x4U_PlainInstr
  | -- pairwise and dot products (page 26)
    I16x8ExtaddPairwiseI8x16S_PlainInstr
  | I16x8ExtaddPairwiseI8x16U_PlainInstr
  | I16x8ExtmulLowI8x16S_PlainInstr
  | I16x8ExtmulLowI8x16U_PlainInstr
  | I16x8ExtmulHighI8x16S_PlainInstr
  | I16x8ExtmulHighI8x16U_PlainInstr
  | I16x8RelaxedDotI8x16I7x16S_PlainInstr
  | I32x4ExtaddPairwiseI16x8S_PlainInstr
  | I32x4ExtaddPairwiseI16x8U_PlainInstr
  | I32x4ExtmulLowI16x8S_PlainInstr
  | I32x4ExtmulLowI16x8U_PlainInstr
  | I32x4ExtmulHighI16x8S_PlainInstr
  | I32x4ExtmulHighI16x8U_PlainInstr
  | I32x4DotI16x8S_PlainInstr
  | I32x4RelaxedDotI8x16I7x16AddS_PlainInstr
  | I64x2ExtmulLowI32x4S_PlainInstr
  | I64x2ExtmulLowI32x4U_PlainInstr
  | I64x2ExtmulHighI32x4S_PlainInstr
  | I64x2ExtmulHighI32x4U_PlainInstr
  deriving (Generic, Eq, Show, Ord)

-- encMem :: Doc ann -> MemIdx -> MemArg -> Doc ann
-- encMem op m arg =
--   if isMemArgEmpty arg
--     then op <+> encodeWat m
--     else op <+> encodeWat m <+> encodeWat arg

-- encMemLane :: Doc ann -> MemIdx -> MemArg -> LaneIdx -> Doc ann
-- encMemLane op m arg lane =
--   if isMemArgEmpty arg
--     then op <+> encodeWat m <+> encodeWat lane
--     else op <+> encodeWat m <+> encodeWat arg <+> encodeWat lane

-- | General WebAssembly instructions.
data Instr
  = Plain_Instr PlainInstr
  | Block_Instr BlockInstr
  | Folded_Instr FoldedInstr
  deriving (Generic, Eq, Show, Ord)

-- | Sequences of instructions.
newtype Instrs = Instrs [Instr]
  deriving (Generic, Eq, Show, Ord)

-- ### 6.5.11 Folded Instructions

-- | Folded instructions are syntactic sugar to group instructions visually.
data FoldedInstr
  = Plain_FoldedInstr PlainInstr [FoldedInstr]
  | Block_FoldedInstr (Maybe Identifier) BlockType [Instr]
  | Loop_FoldedInstr (Maybe Identifier) BlockType [Instr]
  | If_FoldedInstr (Maybe Identifier) BlockType [FoldedInstr] [Instr] [Instr]
  | TryTable_FoldedInstr (Maybe Identifier) BlockType [Catch] [Instr]
  deriving (Generic, Eq, Show, Ord)

-- ### Expressions

-- | Expressions are written as instruction sequences.
newtype Expr = Expr [Instr]
  deriving (Generic, Eq, Show, Ord)

-- ## 6.6 Modules

-- ### 6.6.1 Indices

-- | Indices can be given in either numeric or symbolic form.
data Idx
  = Index_Idx Natural
  | Identifier_Idx Identifier
  deriving (Generic, Eq, Show, Ord)

data TypeIdx = TypeIdx Idx
  deriving (Generic, Eq, Show, Ord)

data FuncIdx = FuncIdx Idx
  deriving (Generic, Eq, Show, Ord)

data GlobalIdx = GlobalIdx Idx
  deriving (Generic, Eq, Show, Ord)

data TableIdx = TableIdx Idx
  deriving (Generic, Eq, Show, Ord)

data MemIdx = MemIdx Idx
  deriving (Generic, Eq, Show, Ord)

data TagIdx = TagIdx Idx
  deriving (Generic, Eq, Show, Ord)

data ElemIdx = ElemIdx Idx
  deriving (Generic, Eq, Show, Ord)

data DataIdx = DataIdx Idx
  deriving (Generic, Eq, Show, Ord)

data LabelIdx = LabelIdx Idx
  deriving (Generic, Eq, Show, Ord)

data LocalIdx = LocalIdx Idx
  deriving (Generic, Eq, Show, Ord)

data FieldIdx = FieldIdx Idx
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.2 Types

-- | A type definition consists of a recursive type.
newtype Type = Type RecType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.3 Tags

-- | Tag definitions bind a symbolic tag identifier.
data Tag = Tag (Maybe Identifier) TagType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.4 Globals

-- | Global definitions bind a symbolic global identifier.
data Global = Global (Maybe Identifier) GlobalType Expr
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.5 Memories

-- | Memory definitions bind a symbolic memory identifier.
data Mem = Mem (Maybe Identifier) MemType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.6 Tables

-- | Table definitions bind a symbolic table identifier.
data Table = Table (Maybe Identifier) TableType Expr
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.7 Functions

-- | Local variables in a function.
data Local = Local (Maybe Identifier) ValType
  deriving (Generic, Eq, Show, Ord)

-- | Function definitions bind a symbolic function identifier and local identifiers for its parameters and locals.
data Func = Func (Maybe Identifier) (Maybe TypeUse) [Local] Expr
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.8 Data Segments

-- | Data segments can be active or passive.
data DataMode
  = Passive_DataMode
  | Active_DataMode MemIdx Expr
  deriving (Generic, Eq, Show, Ord)

-- | Data segments allow for an optional memory index to identify the memory to initialize.
data DataSegment = DataSegment (Maybe Identifier) DataMode ByteString
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.9 Element Segments

-- | Element segment initialization mode.
data ElemMode
  = Passive_ElemMode
  | Active_ElemMode TableIdx Expr
  | Declare_ElemMode
  deriving (Generic, Eq, Show, Ord)

-- | Individual element expressions.
newtype ElemExpr = ElemExpr Expr
  deriving (Generic, Eq, Show, Ord)

-- | A list of elements with reference type.
data ElemList = ElemList RefType [ElemExpr]
  deriving (Generic, Eq, Show, Ord)

-- | Element segments allow for an optional table index to identify the table to initialize.
data ElemSegment = ElemSegment (Maybe Identifier) ElemMode ElemList
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.10 Start Functions

-- | A start function is defined in terms of its index.
newtype Start = Start FuncIdx
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.11 Imports

-- | Imports define the external module, name, and type category.
data Import = Import Name Name ExternalType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.12 Exports

-- | Export category and target index.
data ExternIdx
  = Tag_ExternIdx TagIdx
  | Global_ExternIdx GlobalIdx
  | Memory_ExternIdx MemIdx
  | Table_ExternIdx TableIdx
  | Func_ExternIdx FuncIdx
  deriving (Generic, Eq, Show, Ord)

-- | Exports reveal definitions to the outside environment.
data Export = Export Name ExternIdx
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.13 Modules

-- | Module declarations.
data Decl
  = Type_Decl Type
  | Import_Decl Import
  | Tag_Decl Tag
  | Global_Decl Global
  | Mem_Decl Mem
  | Table_Decl Table
  | Func_Decl Func
  | Data_Decl DataSegment
  | Elem_Decl ElemSegment
  | Start_Decl Start
  | Export_Decl Export
  deriving (Generic, Eq, Show, Ord)

-- | A module consists of a sequence of declarations.
data Module = Module (Maybe Identifier) [Decl]
  deriving (Generic, Eq, Show, Ord)

--------------------------------
-- EncodeWatSexp Instances and Helpers
--------------------------------

limitsSexpList :: Limits -> [Sexp]
limitsSexpList (Limits n mM) = encodeWatSexp n : foldMap (\m -> [Leaf (Text.pack (show m))]) mM

memTypeSexpList :: MemType -> [Sexp]
memTypeSexpList (MemType atM lims) = encodeWatSexpList atM <> limitsSexpList lims

tableTypeSexpList :: TableType -> [Sexp]
tableTypeSexpList (TableType atM lims rt) = encodeWatSexpList atM <> (limitsSexpList lims <> [encodeWatSexp rt])

blockTypeSexpList :: BlockType -> [Sexp]
blockTypeSexpList (Result_BlockType rM) = encodeWatSexpList rM
blockTypeSexpList (TypeUse_BlockType tu) = [encodeWatSexp tu]

memArgSexpList :: MemArg -> [Sexp]
memArgSexpList (MemArg offsetM alignM) = foldMap (\o -> [Leaf ("offset=" <> Text.pack (show o))]) offsetM <> foldMap (\a -> [Leaf ("align=" <> Text.pack (show a))]) alignM

exprSexpList :: Expr -> [Sexp]
exprSexpList (Expr is) = fmap encodeWatSexp is

instrsSexpList :: Instrs -> [Sexp]
instrsSexpList (Instrs is) = fmap encodeWatSexp is

elemListSexpList :: ElemList -> [Sexp]
elemListSexpList (ElemList rt es) =
  encodeWatSexp rt : fmap encodeWatSexp es

dataModeSexpList :: DataMode -> [Sexp]
dataModeSexpList Passive_DataMode = []
dataModeSexpList (Active_DataMode x e) = [Node "memory" [encodeWatSexp x], Node "offset" (exprSexpList e)]

elemModeSexpList :: ElemMode -> [Sexp]
elemModeSexpList Passive_ElemMode = []
elemModeSexpList (Active_ElemMode x e) = [Node "table" [encodeWatSexp x], Node "offset" (exprSexpList e)]
elemModeSexpList Declare_ElemMode = [Leaf "declare"]

encMemSexp :: Text -> MemIdx -> MemArg -> Sexp
encMemSexp op m arg = Node op (encodeWatSexp m : memArgSexpList arg)

encMemLaneSexp :: Text -> MemIdx -> MemArg -> LaneIdx -> Sexp
encMemLaneSexp op m arg lane = Node op (encodeWatSexp m : (memArgSexpList arg <> [encodeWatSexp lane]))

instance EncodeWatSexp Text where
  encodeWatSexp = Leaf

instance EncodeWatSexp Natural where
  encodeWatSexp n = Leaf (Text.show n)

instance EncodeWatSexp Integer where
  encodeWatSexp i = Leaf (Text.show i)

instance EncodeWatSexp Float where
  encodeWatSexp f = Leaf (Text.show f)

instance EncodeWatSexp ByteString where
  encodeWatSexp bs = Leaf (Text.show bs)

instance EncodeWatSexp Name where
  encodeWatSexp (Name t) = Leaf (Text.show t)

instance EncodeWatSexp Identifier where
  encodeWatSexp (Identifier t) = Leaf ("$" <> t)

instance EncodeWatSexp NumType where
  encodeWatSexp I32_NumType = Leaf "i32"
  encodeWatSexp I64_NumType = Leaf "i64"
  encodeWatSexp F32_NumType = Leaf "f32"
  encodeWatSexp F64_NumType = Leaf "f64"

instance EncodeWatSexp VecType where
  encodeWatSexp V128_VecType = Leaf "v128"

instance EncodeWatSexp AbsHeapType where
  encodeWatSexp Any_AbsHeapType = Leaf "any"
  encodeWatSexp Eq_AbsHeapType = Leaf "eq"
  encodeWatSexp I31_AbsHeapType = Leaf "i31"
  encodeWatSexp Struct_AbsHeapType = Leaf "struct"
  encodeWatSexp Array_AbsHeapType = Leaf "array"
  encodeWatSexp None_AbsHeapType = Leaf "none"
  encodeWatSexp Func_AbsHeapType = Leaf "func"
  encodeWatSexp NoFunc_AbsHeapType = Leaf "nofunc"
  encodeWatSexp Exn_AbsHeapType = Leaf "exn"
  encodeWatSexp NoExn_AbsHeapType = Leaf "noexn"
  encodeWatSexp Extern_AbsHeapType = Leaf "extern"
  encodeWatSexp NoExtern_AbsHeapType = Leaf "noextern"

instance EncodeWatSexp HeapType where
  encodeWatSexp (AbsHeapType_HeapType aht) = encodeWatSexp aht
  encodeWatSexp (TypeIdx_HeapType ti) = encodeWatSexp ti

instance EncodeWatSexp Null where
  encodeWatSexp Null = Leaf "null"

instance EncodeWatSexp RefType where
  encodeWatSexp (RefType nullM ht) = Node "ref" (encodeWatSexpList nullM <> [encodeWatSexp ht])

instance EncodeWatSexp ValType where
  encodeWatSexp (NumType_ValType nt) = encodeWatSexp nt
  encodeWatSexp (VecType_ValType vt) = encodeWatSexp vt
  encodeWatSexp (RefType_ValType rt) = encodeWatSexp rt

instance EncodeWatSexp CompType where
  encodeWatSexp (Struct_CompType fs) = Node "struct" (fmap encodeWatSexp fs)
  encodeWatSexp (Array_CompType ft) = Node "array" [encodeWatSexp ft]
  encodeWatSexp (Func_CompType ps rs) = Node "func" (fmap encodeWatSexp ps <> fmap encodeWatSexp rs)

instance EncodeWatSexp Field where
  encodeWatSexp (Field idM ft) = Node "field" (encodeWatSexpList idM <> [encodeWatSexp ft])

instance EncodeWatSexp Param where
  encodeWatSexp (Param idM vt) = Node "param" (encodeWatSexpList idM <> [encodeWatSexp vt])

instance EncodeWatSexp Result where
  encodeWatSexp (Result vt) = Node "result" [encodeWatSexp vt]

instance EncodeWatSexp FieldType where
  encodeWatSexp (FieldType isMut st) =
    if isMut
      then Node "mut" [encodeWatSexp st]
      else encodeWatSexp st

instance EncodeWatSexp StorageType where
  encodeWatSexp (ValType_StorageType vt) = encodeWatSexp vt
  encodeWatSexp (PackType_StorageType pt) = encodeWatSexp pt

instance EncodeWatSexp PackType where
  encodeWatSexp I8_PackType = Leaf "i8"
  encodeWatSexp I16_PackType = Leaf "i16"

instance EncodeWatSexp Final where
  encodeWatSexp Final = Leaf "final"

instance EncodeWatSexp SubType where
  encodeWatSexp (SubType fM tis ct) = Node "sub" (encodeWatSexpList fM <> (fmap encodeWatSexp tis <> [encodeWatSexp ct]))

instance EncodeWatSexp TypeDef where
  encodeWatSexp (TypeDef idM st) = Node "type" (encodeWatSexpList idM <> [encodeWatSexp st])

instance EncodeWatSexp RecType where
  encodeWatSexp (RecType tds) = Node "rec" (fmap encodeWatSexp tds)

instance EncodeWatSexp AddrType where
  encodeWatSexp I32_AddrType = Leaf "i32"
  encodeWatSexp I64_AddrType = Leaf "i64"

instance EncodeWatSexpList Limits where
  encodeWatSexpList = limitsSexpList

instance EncodeWatSexp TagType where
  encodeWatSexp (TagType tu) = encodeWatSexp tu

instance EncodeWatSexp GlobalType where
  encodeWatSexp (GlobalType isMut vt) =
    if isMut
      then Node "mut" [encodeWatSexp vt]
      else encodeWatSexp vt

instance EncodeWatSexpList MemType where
  encodeWatSexpList = memTypeSexpList

instance EncodeWatSexpList TableType where
  encodeWatSexpList = tableTypeSexpList

instance EncodeWatSexp ExternalType where
  encodeWatSexp (Tag_ExternalType idM jt) = Node "tag" (encodeWatSexpList idM <> [encodeWatSexp jt])
  encodeWatSexp (Global_ExternalType idM gt) = Node "global" (encodeWatSexpList idM <> [encodeWatSexp gt])
  encodeWatSexp (Memory_ExternalType idM mt) = Node "memory" (encodeWatSexpList idM <> memTypeSexpList mt)
  encodeWatSexp (Table_ExternalType idM tt) = Node "table" (encodeWatSexpList idM <> tableTypeSexpList tt)
  encodeWatSexp (Func_ExternalType idM tu) = Node "func" (encodeWatSexpList idM <> [encodeWatSexp tu])

instance EncodeWatSexp TypeUse where
  encodeWatSexp (TypeUse ti) = Node "type" [encodeWatSexp ti]

instance EncodeWatSexpList Label where
  encodeWatSexpList (Label idM) = encodeWatSexpList idM

instance EncodeWatSexpList BlockType where
  encodeWatSexpList = blockTypeSexpList

instance EncodeWatSexp Catch where
  encodeWatSexp (Catch tx l) = Node "catch" [encodeWatSexp tx, encodeWatSexp l]
  encodeWatSexp (CatchRef tx l) = Node "catch_ref" [encodeWatSexp tx, encodeWatSexp l]
  encodeWatSexp (CatchAll l) = Node "catch_all" [encodeWatSexp l]
  encodeWatSexp (CatchAllRef l) = Node "catch_all_ref" [encodeWatSexp l]

instance EncodeWatSexp BlockInstr where
  encodeWatSexp (Block_BlockInstr idM bt body _) =
    Node "block" (encodeWatSexpList idM <> (blockTypeSexpList bt <> fmap encodeWatSexp body))
  encodeWatSexp (Loop_BlockInstr idM bt body _) =
    Node "loop" (encodeWatSexpList idM <> (blockTypeSexpList bt <> fmap encodeWatSexp body))
  encodeWatSexp (If_BlockInstr idM bt thenBody _ elseBody _) =
    Node "if" (encodeWatSexpList idM <> (blockTypeSexpList bt <> [Node "then" (fmap encodeWatSexp thenBody)] <> [Node "else" (fmap encodeWatSexp elseBody) | not (null elseBody)]))
  encodeWatSexp (TryTable_BlockInstr idM bt cs body _) =
    Node "try_table" (encodeWatSexpList idM <> (blockTypeSexpList bt <> fmap encodeWatSexp cs <> fmap encodeWatSexp body))

instance EncodeWatSexpList MemArg where
  encodeWatSexpList = memArgSexpList

instance EncodeWatSexp LaneIdx where
  encodeWatSexp (LaneIdx n) = encodeWatSexp n

instance EncodeWatSexp PlainInstr where
  encodeWatSexp Unreachable_PlainInstr = Leaf "unreachable"
  encodeWatSexp Nop_PlainInstr = Leaf "nop"
  encodeWatSexp Drop_PlainInstr = Leaf "drop"
  encodeWatSexp (Select_PlainInstr rsM) = Node "select" (foldMap (fmap encodeWatSexp) rsM)
  encodeWatSexp (Br_PlainInstr l) = Node "br" [encodeWatSexp l]
  encodeWatSexp (BrIf_PlainInstr l) = Node "br_if" [encodeWatSexp l]
  encodeWatSexp (BrTable_PlainInstr ls l) = Node "br_table" (fmap encodeWatSexp ls <> [encodeWatSexp l])
  encodeWatSexp Return_PlainInstr = Leaf "return"
  encodeWatSexp (Call_PlainInstr f) = Node "call" [encodeWatSexp f]
  encodeWatSexp (ReturnCall_PlainInstr f) = Node "return_call" [encodeWatSexp f]
  encodeWatSexp (CallIndirect_PlainInstr t tu) = Node "call_indirect" [encodeWatSexp t, encodeWatSexp tu]
  encodeWatSexp (ReturnCallIndirect_PlainInstr t tu) = Node "return_call_indirect" [encodeWatSexp t, encodeWatSexp tu]
  encodeWatSexp (LocalGet_PlainInstr l) = Node "local.get" [encodeWatSexp l]
  encodeWatSexp (LocalSet_PlainInstr l) = Node "local.set" [encodeWatSexp l]
  encodeWatSexp (LocalTee_PlainInstr l) = Node "local.tee" [encodeWatSexp l]
  encodeWatSexp (GlobalGet_PlainInstr g) = Node "global.get" [encodeWatSexp g]
  encodeWatSexp (GlobalSet_PlainInstr g) = Node "global.set" [encodeWatSexp g]
  encodeWatSexp (TableGet_PlainInstr t) = Node "table.get" [encodeWatSexp t]
  encodeWatSexp (TableSet_PlainInstr t) = Node "table.set" [encodeWatSexp t]
  encodeWatSexp (TableSize_PlainInstr t) = Node "table.size" [encodeWatSexp t]
  encodeWatSexp (TableGrow_PlainInstr t) = Node "table.grow" [encodeWatSexp t]
  encodeWatSexp (TableFill_PlainInstr t) = Node "table.fill" [encodeWatSexp t]
  encodeWatSexp (TableCopy_PlainInstr t1 t2) = Node "table.copy" [encodeWatSexp t1, encodeWatSexp t2]
  encodeWatSexp (TableInit_PlainInstr t e) = Node "table.init" [encodeWatSexp t, encodeWatSexp e]
  encodeWatSexp (ElemDrop_PlainInstr e) = Node "elem.drop" [encodeWatSexp e]
  encodeWatSexp (I32Load_PlainInstr m arg) = encMemSexp "i32.load" m arg
  encodeWatSexp (I64Load_PlainInstr m arg) = encMemSexp "i64.load" m arg
  encodeWatSexp (F32Load_PlainInstr m arg) = encMemSexp "f32.load" m arg
  encodeWatSexp (F64Load_PlainInstr m arg) = encMemSexp "f64.load" m arg
  encodeWatSexp (I32Load8S_PlainInstr m arg) = encMemSexp "i32.load8_s" m arg
  encodeWatSexp (I32Load8U_PlainInstr m arg) = encMemSexp "i32.load8_u" m arg
  encodeWatSexp (I32Load16S_PlainInstr m arg) = encMemSexp "i32.load16_s" m arg
  encodeWatSexp (I32Load16U_PlainInstr m arg) = encMemSexp "i32.load16_u" m arg
  encodeWatSexp (I64Load8S_PlainInstr m arg) = encMemSexp "i64.load8_s" m arg
  encodeWatSexp (I64Load8U_PlainInstr m arg) = encMemSexp "i64.load8_u" m arg
  encodeWatSexp (I64Load16S_PlainInstr m arg) = encMemSexp "i64.load16_s" m arg
  encodeWatSexp (I64Load16U_PlainInstr m arg) = encMemSexp "i64.load16_u" m arg
  encodeWatSexp (I64Load32S_PlainInstr m arg) = encMemSexp "i64.load32_s" m arg
  encodeWatSexp (I64Load32U_PlainInstr m arg) = encMemSexp "i64.load32_u" m arg
  encodeWatSexp (V128Load_PlainInstr m arg) = encMemSexp "v128.load" m arg
  encodeWatSexp (V128Load8x8S_PlainInstr m arg) = encMemSexp "v128.load8x8_s" m arg
  encodeWatSexp (V128Load8x8U_PlainInstr m arg) = encMemSexp "v128.load8x8_u" m arg
  encodeWatSexp (V128Load16x4S_PlainInstr m arg) = encMemSexp "v128.load16x4_s" m arg
  encodeWatSexp (V128Load16x4U_PlainInstr m arg) = encMemSexp "v128.load16x4_u" m arg
  encodeWatSexp (V128Load32x2S_PlainInstr m arg) = encMemSexp "v128.load32x2_s" m arg
  encodeWatSexp (V128Load32x2U_PlainInstr m arg) = encMemSexp "v128.load32x2_u" m arg
  encodeWatSexp (V128Load8Splat_PlainInstr m arg) = encMemSexp "v128.load8_splat" m arg
  encodeWatSexp (V128Load16Splat_PlainInstr m arg) = encMemSexp "v128.load16_splat" m arg
  encodeWatSexp (V128Load32Splat_PlainInstr m arg) = encMemSexp "v128.load32_splat" m arg
  encodeWatSexp (V128Load64Splat_PlainInstr m arg) = encMemSexp "v128.load64_splat" m arg
  encodeWatSexp (V128Load32Zero_PlainInstr m arg) = encMemSexp "v128.load32_zero" m arg
  encodeWatSexp (V128Load64Zero_PlainInstr m arg) = encMemSexp "v128.load64_zero" m arg
  encodeWatSexp (V128Load8Lane_PlainInstr m arg lane) = encMemLaneSexp "v128.load8_lane" m arg lane
  encodeWatSexp (V128Load16Lane_PlainInstr m arg lane) = encMemLaneSexp "v128.load16_lane" m arg lane
  encodeWatSexp (V128Load32Lane_PlainInstr m arg lane) = encMemLaneSexp "v128.load32_lane" m arg lane
  encodeWatSexp (V128Load64Lane_PlainInstr m arg lane) = encMemLaneSexp "v128.load64_lane" m arg lane
  encodeWatSexp (I32Store_PlainInstr m arg) = encMemSexp "i32.store" m arg
  encodeWatSexp (I64Store_PlainInstr m arg) = encMemSexp "i64.store" m arg
  encodeWatSexp (F32Store_PlainInstr m arg) = encMemSexp "f32.store" m arg
  encodeWatSexp (F64Store_PlainInstr m arg) = encMemSexp "f64.store" m arg
  encodeWatSexp (I32Store8_PlainInstr m arg) = encMemSexp "i32.store8" m arg
  encodeWatSexp (I32Store16_PlainInstr m arg) = encMemSexp "i32.store16" m arg
  encodeWatSexp (I64Store8_PlainInstr m arg) = encMemSexp "i64.store8" m arg
  encodeWatSexp (I64Store16_PlainInstr m arg) = encMemSexp "i64.store16" m arg
  encodeWatSexp (I64Store32_PlainInstr m arg) = encMemSexp "i64.store32" m arg
  encodeWatSexp (V128Store_PlainInstr m arg) = encMemSexp "v128.store" m arg
  encodeWatSexp (V128Store8Lane_PlainInstr m arg lane) = encMemLaneSexp "v128.store8_lane" m arg lane
  encodeWatSexp (V128Store16Lane_PlainInstr m arg lane) = encMemLaneSexp "v128.store16_lane" m arg lane
  encodeWatSexp (V128Store32Lane_PlainInstr m arg lane) = encMemLaneSexp "v128.store32_lane" m arg lane
  encodeWatSexp (V128Store64Lane_PlainInstr m arg lane) = encMemLaneSexp "v128.store64_lane" m arg lane
  encodeWatSexp (MemorySize_PlainInstr m) = Node "memory.size" [encodeWatSexp m]
  encodeWatSexp (MemoryGrow_PlainInstr m) = Node "memory.grow" [encodeWatSexp m]
  encodeWatSexp (MemoryFill_PlainInstr m) = Node "memory.fill" [encodeWatSexp m]
  encodeWatSexp (MemoryCopy_PlainInstr m1 m2) = Node "memory.copy" [encodeWatSexp m1, encodeWatSexp m2]
  encodeWatSexp (MemoryInit_PlainInstr m d) = Node "memory.init" [encodeWatSexp m, encodeWatSexp d]
  encodeWatSexp (DataDrop_PlainInstr d) = Node "data.drop" [encodeWatSexp d]
  encodeWatSexp (RefNull_PlainInstr ht) = Node "ref.null" [encodeWatSexp ht]
  encodeWatSexp (RefFunc_PlainInstr f) = Node "ref.func" [encodeWatSexp f]
  encodeWatSexp RefIsNull_PlainInstr = Leaf "ref.is_null"
  encodeWatSexp RefAsNonNull_PlainInstr = Leaf "ref.as_non_null"
  encodeWatSexp RefEq_PlainInstr = Leaf "ref.eq"
  encodeWatSexp (RefTest_PlainInstr rt) = Node "ref.test" [encodeWatSexp rt]
  encodeWatSexp (RefCast_PlainInstr rt) = Node "ref.cast" [encodeWatSexp rt]
  encodeWatSexp RefI31_PlainInstr = Leaf "ref.i31"
  encodeWatSexp I31GetS_PlainInstr = Leaf "i31.get_s"
  encodeWatSexp I31GetU_PlainInstr = Leaf "i31.get_u"
  encodeWatSexp (StructNew_PlainInstr t) = Node "struct.new" [encodeWatSexp t]
  encodeWatSexp (StructNewDefault_PlainInstr t) = Node "struct.new_default" [encodeWatSexp t]
  encodeWatSexp (StructGet_PlainInstr t f) = Node "struct.get" [encodeWatSexp t, encodeWatSexp f]
  encodeWatSexp (StructGetS_PlainInstr t f) = Node "struct.get_s" [encodeWatSexp t, encodeWatSexp f]
  encodeWatSexp (StructGetU_PlainInstr t f) = Node "struct.get_u" [encodeWatSexp t, encodeWatSexp f]
  encodeWatSexp (StructSet_PlainInstr t f) = Node "struct.set" [encodeWatSexp t, encodeWatSexp f]
  encodeWatSexp (ArrayNew_PlainInstr t) = Node "array.new" [encodeWatSexp t]
  encodeWatSexp (ArrayNewDefault_PlainInstr t) = Node "array.new_default" [encodeWatSexp t]
  encodeWatSexp (ArrayNewFixed_PlainInstr t n) = Node "array.new_fixed" [encodeWatSexp t, encodeWatSexp n]
  encodeWatSexp (ArrayNewData_PlainInstr t d) = Node "array.new_data" [encodeWatSexp t, encodeWatSexp d]
  encodeWatSexp (ArrayNewElem_PlainInstr t e) = Node "array.new_elem" [encodeWatSexp t, encodeWatSexp e]
  encodeWatSexp (ArrayGet_PlainInstr t) = Node "array.get" [encodeWatSexp t]
  encodeWatSexp (ArrayGetS_PlainInstr t) = Node "array.get_s" [encodeWatSexp t]
  encodeWatSexp (ArrayGetU_PlainInstr t) = Node "array.get_u" [encodeWatSexp t]
  encodeWatSexp (ArraySet_PlainInstr t) = Node "array.set" [encodeWatSexp t]
  encodeWatSexp ArrayLen_PlainInstr = Leaf "array.len"
  encodeWatSexp (ArrayFill_PlainInstr t) = Node "array.fill" [encodeWatSexp t]
  encodeWatSexp (ArrayCopy_PlainInstr t1 t2) = Node "array.copy" [encodeWatSexp t1, encodeWatSexp t2]
  encodeWatSexp (ArrayInitData_PlainInstr t d) = Node "array.init_data" [encodeWatSexp t, encodeWatSexp d]
  encodeWatSexp (ArrayInitElem_PlainInstr t e) = Node "array.init_elem" [encodeWatSexp t, encodeWatSexp e]
  encodeWatSexp AnyConvertExtern_PlainInstr = Leaf "any.convert_extern"
  encodeWatSexp ExternConvertAny_PlainInstr = Leaf "extern.convert_any"
  encodeWatSexp (I32Const_PlainInstr c) = Node "i32.const" [encodeWatSexp c]
  encodeWatSexp (I64Const_PlainInstr c) = Node "i64.const" [encodeWatSexp c]
  encodeWatSexp (F32Const_PlainInstr c) = Node "f32.const" [encodeWatSexp c]
  encodeWatSexp (F64Const_PlainInstr c) = Node "f64.const" [encodeWatSexp c]
  encodeWatSexp (V128Const_PlainInstr shape cs) = Node "v128.const" (Leaf shape : fmap encodeWatSexp cs)
  encodeWatSexp (I8x16Shuffle_PlainInstr lanes) = Node "i8x16.shuffle" (fmap encodeWatSexp lanes)
  encodeWatSexp (I8x16ExtractLaneS_PlainInstr lane) = Node "i8x16.extract_lane_s" [encodeWatSexp lane]
  encodeWatSexp (I8x16ExtractLaneU_PlainInstr lane) = Node "i8x16.extract_lane_u" [encodeWatSexp lane]
  encodeWatSexp (I16x8ExtractLaneS_PlainInstr lane) = Node "i16x8.extract_lane_s" [encodeWatSexp lane]
  encodeWatSexp (I16x8ExtractLaneU_PlainInstr lane) = Node "i16x8.extract_lane_u" [encodeWatSexp lane]
  encodeWatSexp (I32x4ExtractLane_PlainInstr lane) = Node "i32x4.extract_lane" [encodeWatSexp lane]
  encodeWatSexp (I64x2ExtractLane_PlainInstr lane) = Node "i64x2.extract_lane" [encodeWatSexp lane]
  encodeWatSexp (F32x4ExtractLane_PlainInstr lane) = Node "f32x4.extract_lane" [encodeWatSexp lane]
  encodeWatSexp (F64x2ExtractLane_PlainInstr lane) = Node "f64x2.extract_lane" [encodeWatSexp lane]
  encodeWatSexp (I8x16ReplaceLane_PlainInstr lane) = Node "i8x16.replace_lane" [encodeWatSexp lane]
  encodeWatSexp (I16x8ReplaceLane_PlainInstr lane) = Node "i16x8.replace_lane" [encodeWatSexp lane]
  encodeWatSexp (I32x4ReplaceLane_PlainInstr lane) = Node "i32x4.replace_lane" [encodeWatSexp lane]
  encodeWatSexp (I64x2ReplaceLane_PlainInstr lane) = Node "i64x2.replace_lane" [encodeWatSexp lane]
  encodeWatSexp (F32x4ReplaceLane_PlainInstr lane) = Node "f32x4.replace_lane" [encodeWatSexp lane]
  encodeWatSexp (F64x2ReplaceLane_PlainInstr lane) = Node "f64x2.replace_lane" [encodeWatSexp lane]
  encodeWatSexp I32Eqz_PlainInstr = Leaf "i32.eqz"
  encodeWatSexp I32Eq_PlainInstr = Leaf "i32.eq"
  encodeWatSexp I32Ne_PlainInstr = Leaf "i32.ne"
  encodeWatSexp I32LtS_PlainInstr = Leaf "i32.lt_s"
  encodeWatSexp I32LtU_PlainInstr = Leaf "i32.lt_u"
  encodeWatSexp I32GtS_PlainInstr = Leaf "i32.gt_s"
  encodeWatSexp I32GtU_PlainInstr = Leaf "i32.gt_u"
  encodeWatSexp I32LeS_PlainInstr = Leaf "i32.le_s"
  encodeWatSexp I32LeU_PlainInstr = Leaf "i32.le_u"
  encodeWatSexp I32GeS_PlainInstr = Leaf "i32.ge_s"
  encodeWatSexp I32GeU_PlainInstr = Leaf "i32.ge_u"
  encodeWatSexp I32Clz_PlainInstr = Leaf "i32.clz"
  encodeWatSexp I32Ctz_PlainInstr = Leaf "i32.ctz"
  encodeWatSexp I32Popcnt_PlainInstr = Leaf "i32.popcnt"
  encodeWatSexp I32Extend8S_PlainInstr = Leaf "i32.extend8_s"
  encodeWatSexp I32Extend16S_PlainInstr = Leaf "i32.extend16_s"
  encodeWatSexp I32Add_PlainInstr = Leaf "i32.add"
  encodeWatSexp I32Sub_PlainInstr = Leaf "i32.sub"
  encodeWatSexp I32Mul_PlainInstr = Leaf "i32.mul"
  encodeWatSexp I32DivS_PlainInstr = Leaf "i32.div_s"
  encodeWatSexp I32DivU_PlainInstr = Leaf "i32.div_u"
  encodeWatSexp I32RemS_PlainInstr = Leaf "i32.rem_s"
  encodeWatSexp I32RemU_PlainInstr = Leaf "i32.rem_u"
  encodeWatSexp I32And_PlainInstr = Leaf "i32.and"
  encodeWatSexp I32Or_PlainInstr = Leaf "i32.or"
  encodeWatSexp I32Xor_PlainInstr = Leaf "i32.xor"
  encodeWatSexp I32Shl_PlainInstr = Leaf "i32.shl"
  encodeWatSexp I32ShrS_PlainInstr = Leaf "i32.shr_s"
  encodeWatSexp I32ShrU_PlainInstr = Leaf "i32.shr_u"
  encodeWatSexp I32Rotl_PlainInstr = Leaf "i32.rotl"
  encodeWatSexp I32Rotr_PlainInstr = Leaf "i32.rotr"
  encodeWatSexp I64Eqz_PlainInstr = Leaf "i64.eqz"
  encodeWatSexp I64Eq_PlainInstr = Leaf "i64.eq"
  encodeWatSexp I64Ne_PlainInstr = Leaf "i64.ne"
  encodeWatSexp I64LtS_PlainInstr = Leaf "i64.lt_s"
  encodeWatSexp I64LtU_PlainInstr = Leaf "i64.lt_u"
  encodeWatSexp I64GtS_PlainInstr = Leaf "i64.gt_s"
  encodeWatSexp I64GtU_PlainInstr = Leaf "i64.gt_u"
  encodeWatSexp I64LeS_PlainInstr = Leaf "i64.le_s"
  encodeWatSexp I64LeU_PlainInstr = Leaf "i64.le_u"
  encodeWatSexp I64GeS_PlainInstr = Leaf "i64.ge_s"
  encodeWatSexp I64GeU_PlainInstr = Leaf "i64.ge_u"
  encodeWatSexp I64Clz_PlainInstr = Leaf "i64.clz"
  encodeWatSexp I64Ctz_PlainInstr = Leaf "i64.ctz"
  encodeWatSexp I64Popcnt_PlainInstr = Leaf "i64.popcnt"
  encodeWatSexp I64Extend8S_PlainInstr = Leaf "i64.extend8_s"
  encodeWatSexp I64Extend16S_PlainInstr = Leaf "i64.extend16_s"
  encodeWatSexp I64Extend32S_PlainInstr = Leaf "i64.extend32_s"
  encodeWatSexp I64Add_PlainInstr = Leaf "i64.add"
  encodeWatSexp I64Sub_PlainInstr = Leaf "i64.sub"
  encodeWatSexp I64Mul_PlainInstr = Leaf "i64.mul"
  encodeWatSexp I64DivS_PlainInstr = Leaf "i64.div_s"
  encodeWatSexp I64DivU_PlainInstr = Leaf "i64.div_u"
  encodeWatSexp I64RemS_PlainInstr = Leaf "i64.rem_s"
  encodeWatSexp I64RemU_PlainInstr = Leaf "i64.rem_u"
  encodeWatSexp I64And_PlainInstr = Leaf "i64.and"
  encodeWatSexp I64Or_PlainInstr = Leaf "i64.or"
  encodeWatSexp I64Xor_PlainInstr = Leaf "i64.xor"
  encodeWatSexp I64Shl_PlainInstr = Leaf "i64.shl"
  encodeWatSexp I64ShrS_PlainInstr = Leaf "i64.shr_s"
  encodeWatSexp I64ShrU_PlainInstr = Leaf "i64.shr_u"
  encodeWatSexp I64Rotl_PlainInstr = Leaf "i64.rotl"
  encodeWatSexp I64Rotr_PlainInstr = Leaf "i64.rotr"
  encodeWatSexp F32Eq_PlainInstr = Leaf "f32.eq"
  encodeWatSexp F32Ne_PlainInstr = Leaf "f32.ne"
  encodeWatSexp F32Lt_PlainInstr = Leaf "f32.lt"
  encodeWatSexp F32Gt_PlainInstr = Leaf "f32.gt"
  encodeWatSexp F32Le_PlainInstr = Leaf "f32.le"
  encodeWatSexp F32Ge_PlainInstr = Leaf "f32.ge"
  encodeWatSexp F32Abs_PlainInstr = Leaf "f32.abs"
  encodeWatSexp F32Neg_PlainInstr = Leaf "f32.neg"
  encodeWatSexp F32Sqrt_PlainInstr = Leaf "f32.sqrt"
  encodeWatSexp F32Ceil_PlainInstr = Leaf "f32.ceil"
  encodeWatSexp F32Floor_PlainInstr = Leaf "f32.floor"
  encodeWatSexp F32Trunc_PlainInstr = Leaf "f32.trunc"
  encodeWatSexp F32Nearest_PlainInstr = Leaf "f32.nearest"
  encodeWatSexp F32Add_PlainInstr = Leaf "f32.add"
  encodeWatSexp F32Sub_PlainInstr = Leaf "f32.sub"
  encodeWatSexp F32Mul_PlainInstr = Leaf "f32.mul"
  encodeWatSexp F32Div_PlainInstr = Leaf "f32.div"
  encodeWatSexp F32Min_PlainInstr = Leaf "f32.min"
  encodeWatSexp F32Max_PlainInstr = Leaf "f32.max"
  encodeWatSexp F32Copysign_PlainInstr = Leaf "f32.copysign"
  encodeWatSexp F64Eq_PlainInstr = Leaf "f64.eq"
  encodeWatSexp F64Ne_PlainInstr = Leaf "f64.ne"
  encodeWatSexp F64Lt_PlainInstr = Leaf "f64.lt"
  encodeWatSexp F64Gt_PlainInstr = Leaf "f64.gt"
  encodeWatSexp F64Le_PlainInstr = Leaf "f64.le"
  encodeWatSexp F64Ge_PlainInstr = Leaf "f64.ge"
  encodeWatSexp F64Abs_PlainInstr = Leaf "f64.abs"
  encodeWatSexp F64Neg_PlainInstr = Leaf "f64.neg"
  encodeWatSexp F64Sqrt_PlainInstr = Leaf "f64.sqrt"
  encodeWatSexp F64Ceil_PlainInstr = Leaf "f64.ceil"
  encodeWatSexp F64Floor_PlainInstr = Leaf "f64.floor"
  encodeWatSexp F64Trunc_PlainInstr = Leaf "f64.trunc"
  encodeWatSexp F64Nearest_PlainInstr = Leaf "f64.nearest"
  encodeWatSexp F64Add_PlainInstr = Leaf "f64.add"
  encodeWatSexp F64Sub_PlainInstr = Leaf "f64.sub"
  encodeWatSexp F64Mul_PlainInstr = Leaf "f64.mul"
  encodeWatSexp F64Div_PlainInstr = Leaf "f64.div"
  encodeWatSexp F64Min_PlainInstr = Leaf "f64.min"
  encodeWatSexp F64Max_PlainInstr = Leaf "f64.max"
  encodeWatSexp F64Copysign_PlainInstr = Leaf "f64.copysign"
  encodeWatSexp I32WrapI64_PlainInstr = Leaf "i32.wrap_i64"
  encodeWatSexp I32TruncF32S_PlainInstr = Leaf "i32.trunc_f32_s"
  encodeWatSexp I32TruncF32U_PlainInstr = Leaf "i32.trunc_f32_u"
  encodeWatSexp I32TruncF64S_PlainInstr = Leaf "i32.trunc_f64_s"
  encodeWatSexp I32TruncF64U_PlainInstr = Leaf "i32.trunc_f64_u"
  encodeWatSexp I32TruncSatF32S_PlainInstr = Leaf "i32.trunc_sat_f32_s"
  encodeWatSexp I32TruncSatF32U_PlainInstr = Leaf "i32.trunc_sat_f32_u"
  encodeWatSexp I32TruncSatF64S_PlainInstr = Leaf "i32.trunc_sat_f64_s"
  encodeWatSexp I32TruncSatF64U_PlainInstr = Leaf "i32.trunc_sat_f64_u"
  encodeWatSexp I64ExtendI32S_PlainInstr = Leaf "i64.extend_i32_s"
  encodeWatSexp I64ExtendI32U_PlainInstr = Leaf "i64.extend_i32_u"
  encodeWatSexp I64TruncF32S_PlainInstr = Leaf "i64.trunc_f32_s"
  encodeWatSexp I64TruncF32U_PlainInstr = Leaf "i64.trunc_f32_u"
  encodeWatSexp I64TruncF64S_PlainInstr = Leaf "i64.trunc_f64_s"
  encodeWatSexp I64TruncF64U_PlainInstr = Leaf "i64.trunc_f64_u"
  encodeWatSexp I64TruncSatF32S_PlainInstr = Leaf "i64.trunc_sat_f32_s"
  encodeWatSexp I64TruncSatF32U_PlainInstr = Leaf "i64.trunc_sat_f32_u"
  encodeWatSexp I64TruncSatF64S_PlainInstr = Leaf "i64.trunc_sat_f64_s"
  encodeWatSexp I64TruncSatF64U_PlainInstr = Leaf "i64.trunc_sat_f64_u"
  encodeWatSexp F32DemoteF64_PlainInstr = Leaf "f32.demote_f64"
  encodeWatSexp F32ConvertI32S_PlainInstr = Leaf "f32.convert_i32_s"
  encodeWatSexp F32ConvertI32U_PlainInstr = Leaf "f32.convert_i32_u"
  encodeWatSexp F32ConvertI64S_PlainInstr = Leaf "f32.convert_i64_s"
  encodeWatSexp F32ConvertI64U_PlainInstr = Leaf "f32.convert_i64_u"
  encodeWatSexp F64PromoteF32_PlainInstr = Leaf "f64.promote_f32"
  encodeWatSexp F64ConvertI32S_PlainInstr = Leaf "f64.convert_i32_s"
  encodeWatSexp F64ConvertI32U_PlainInstr = Leaf "f64.convert_i32_u"
  encodeWatSexp F64ConvertI64S_PlainInstr = Leaf "f64.convert_i64_s"
  encodeWatSexp F64ConvertI64U_PlainInstr = Leaf "f64.convert_i64_u"
  encodeWatSexp I32ReinterpretF32_PlainInstr = Leaf "i32.reinterpret_f32"
  encodeWatSexp I64ReinterpretF64_PlainInstr = Leaf "i64.reinterpret_f64"
  encodeWatSexp F32ReinterpretI32_PlainInstr = Leaf "f32.reinterpret_i32"
  encodeWatSexp F64ReinterpretI64_PlainInstr = Leaf "f64.reinterpret_i64"
  encodeWatSexp I8x16Swizzle_PlainInstr = Leaf "i8x16.swizzle"
  encodeWatSexp I8x16RelaxedSwizzle_PlainInstr = Leaf "i8x16.relaxed_swizzle"
  encodeWatSexp I8x16Splat_PlainInstr = Leaf "i8x16.splat"
  encodeWatSexp I16x8Splat_PlainInstr = Leaf "i16x8.splat"
  encodeWatSexp I32x4Splat_PlainInstr = Leaf "i32x4.splat"
  encodeWatSexp I64x2Splat_PlainInstr = Leaf "i64x2.splat"
  encodeWatSexp F32x4Splat_PlainInstr = Leaf "f32x4.splat"
  encodeWatSexp F64x2Splat_PlainInstr = Leaf "f64x2.splat"
  encodeWatSexp V128AnyTrue_PlainInstr = Leaf "v128.any_true"
  encodeWatSexp V128Not_PlainInstr = Leaf "v128.not"
  encodeWatSexp V128And_PlainInstr = Leaf "v128.and"
  encodeWatSexp V128Andnot_PlainInstr = Leaf "v128.andnot"
  encodeWatSexp V128Or_PlainInstr = Leaf "v128.or"
  encodeWatSexp V128Xor_PlainInstr = Leaf "v128.xor"
  encodeWatSexp V128Bitselect_PlainInstr = Leaf "v128.bitselect"
  encodeWatSexp I8x16AllTrue_PlainInstr = Leaf "i8x16.all_true"
  encodeWatSexp I8x16Eq_PlainInstr = Leaf "i8x16.eq"
  encodeWatSexp I8x16Ne_PlainInstr = Leaf "i8x16.ne"
  encodeWatSexp I8x16LtS_PlainInstr = Leaf "i8x16.lt_s"
  encodeWatSexp I8x16LtU_PlainInstr = Leaf "i8x16.lt_u"
  encodeWatSexp I8x16GtS_PlainInstr = Leaf "i8x16.gt_s"
  encodeWatSexp I8x16GtU_PlainInstr = Leaf "i8x16.gt_u"
  encodeWatSexp I8x16LeS_PlainInstr = Leaf "i8x16.le_s"
  encodeWatSexp I8x16LeU_PlainInstr = Leaf "i8x16.le_u"
  encodeWatSexp I8x16GeS_PlainInstr = Leaf "i8x16.ge_s"
  encodeWatSexp I8x16GeU_PlainInstr = Leaf "i8x16.ge_u"
  encodeWatSexp I8x16Abs_PlainInstr = Leaf "i8x16.abs"
  encodeWatSexp I8x16Neg_PlainInstr = Leaf "i8x16.neg"
  encodeWatSexp I8x16Popcnt_PlainInstr = Leaf "i8x16.popcnt"
  encodeWatSexp I8x16Add_PlainInstr = Leaf "i8x16.add"
  encodeWatSexp I8x16AddSatS_PlainInstr = Leaf "i8x16.add_sat_s"
  encodeWatSexp I8x16AddSatU_PlainInstr = Leaf "i8x16.add_sat_u"
  encodeWatSexp I8x16Sub_PlainInstr = Leaf "i8x16.sub"
  encodeWatSexp I8x16SubSatS_PlainInstr = Leaf "i8x16.sub_sat_s"
  encodeWatSexp I8x16SubSatU_PlainInstr = Leaf "i8x16.sub_sat_u"
  encodeWatSexp I8x16MinS_PlainInstr = Leaf "i8x16.min_s"
  encodeWatSexp I8x16MinU_PlainInstr = Leaf "i8x16.min_u"
  encodeWatSexp I8x16MaxS_PlainInstr = Leaf "i8x16.max_s"
  encodeWatSexp I8x16MaxU_PlainInstr = Leaf "i8x16.max_u"
  encodeWatSexp I8x16AvgrU_PlainInstr = Leaf "i8x16.avgr_u"
  encodeWatSexp I8x16RelaxedLaneselect_PlainInstr = Leaf "i8x16.relaxed_laneselect"
  encodeWatSexp I8x16Shl_PlainInstr = Leaf "i8x16.shl"
  encodeWatSexp I8x16ShrS_PlainInstr = Leaf "i8x16.shr_s"
  encodeWatSexp I8x16ShrU_PlainInstr = Leaf "i8x16.shr_u"
  encodeWatSexp I8x16Bitmask_PlainInstr = Leaf "i8x16.bitmask"
  encodeWatSexp I8x16NarrowI16x8S_PlainInstr = Leaf "i8x16.narrow_i16x8_s"
  encodeWatSexp I8x16NarrowI16x8U_PlainInstr = Leaf "i8x16.narrow_i16x8_u"
  encodeWatSexp I16x8AllTrue_PlainInstr = Leaf "i16x8.all_true"
  encodeWatSexp I16x8Eq_PlainInstr = Leaf "i16x8.eq"
  encodeWatSexp I16x8Ne_PlainInstr = Leaf "i16x8.ne"
  encodeWatSexp I16x8LtS_PlainInstr = Leaf "i16x8.lt_s"
  encodeWatSexp I16x8LtU_PlainInstr = Leaf "i16x8.lt_u"
  encodeWatSexp I16x8GtS_PlainInstr = Leaf "i16x8.gt_s"
  encodeWatSexp I16x8GtU_PlainInstr = Leaf "i16x8.gt_u"
  encodeWatSexp I16x8LeS_PlainInstr = Leaf "i16x8.le_s"
  encodeWatSexp I16x8LeU_PlainInstr = Leaf "i16x8.le_u"
  encodeWatSexp I16x8GeS_PlainInstr = Leaf "i16x8.ge_s"
  encodeWatSexp I16x8GeU_PlainInstr = Leaf "i16x8.ge_u"
  encodeWatSexp I16x8Abs_PlainInstr = Leaf "i16x8.abs"
  encodeWatSexp I16x8Neg_PlainInstr = Leaf "i16x8.neg"
  encodeWatSexp I16x8Add_PlainInstr = Leaf "i16x8.add"
  encodeWatSexp I16x8AddSatS_PlainInstr = Leaf "i16x8.add_sat_s"
  encodeWatSexp I16x8AddSatU_PlainInstr = Leaf "i16x8.add_sat_u"
  encodeWatSexp I16x8Sub_PlainInstr = Leaf "i16x8.sub"
  encodeWatSexp I16x8SubSatS_PlainInstr = Leaf "i16x8.sub_sat_s"
  encodeWatSexp I16x8SubSatU_PlainInstr = Leaf "i16x8.sub_sat_u"
  encodeWatSexp I16x8Mul_PlainInstr = Leaf "i16x8.mul"
  encodeWatSexp I16x8MinS_PlainInstr = Leaf "i16x8.min_s"
  encodeWatSexp I16x8MinU_PlainInstr = Leaf "i16x8.min_u"
  encodeWatSexp I16x8MaxS_PlainInstr = Leaf "i16x8.max_s"
  encodeWatSexp I16x8MaxU_PlainInstr = Leaf "i16x8.max_u"
  encodeWatSexp I16x8AvgrU_PlainInstr = Leaf "i16x8.avgr_u"
  encodeWatSexp I16x8Q15mulrSatS_PlainInstr = Leaf "i16x8.q15mulr_sat_s"
  encodeWatSexp I16x8RelaxedQ15mulrS_PlainInstr = Leaf "i16x8.relaxed_q15mulr_s"
  encodeWatSexp I16x8RelaxedLaneselect_PlainInstr = Leaf "i16x8.relaxed_laneselect"
  encodeWatSexp I16x8Shl_PlainInstr = Leaf "i16x8.shl"
  encodeWatSexp I16x8ShrS_PlainInstr = Leaf "i16x8.shr_s"
  encodeWatSexp I16x8ShrU_PlainInstr = Leaf "i16x8.shr_u"
  encodeWatSexp I16x8Bitmask_PlainInstr = Leaf "i16x8.bitmask"
  encodeWatSexp I16x8NarrowI32x4S_PlainInstr = Leaf "i16x8.narrow_i32x4_s"
  encodeWatSexp I16x8NarrowI32x4U_PlainInstr = Leaf "i16x8.narrow_i32x4_u"
  encodeWatSexp I32x4AllTrue_PlainInstr = Leaf "i32x4.all_true"
  encodeWatSexp I32x4Eq_PlainInstr = Leaf "i32x4.eq"
  encodeWatSexp I32x4Ne_PlainInstr = Leaf "i32x4.ne"
  encodeWatSexp I32x4LtS_PlainInstr = Leaf "i32x4.lt_s"
  encodeWatSexp I32x4LtU_PlainInstr = Leaf "i32x4.lt_u"
  encodeWatSexp I32x4GtS_PlainInstr = Leaf "i32x4.gt_s"
  encodeWatSexp I32x4GtU_PlainInstr = Leaf "i32x4.gt_u"
  encodeWatSexp I32x4LeS_PlainInstr = Leaf "i32x4.le_s"
  encodeWatSexp I32x4LeU_PlainInstr = Leaf "i32x4.le_u"
  encodeWatSexp I32x4GeS_PlainInstr = Leaf "i32x4.ge_s"
  encodeWatSexp I32x4GeU_PlainInstr = Leaf "i32x4.ge_u"
  encodeWatSexp I32x4Abs_PlainInstr = Leaf "i32x4.abs"
  encodeWatSexp I32x4Neg_PlainInstr = Leaf "i32x4.neg"
  encodeWatSexp I32x4Add_PlainInstr = Leaf "i32x4.add"
  encodeWatSexp I32x4Sub_PlainInstr = Leaf "i32x4.sub"
  encodeWatSexp I32x4Mul_PlainInstr = Leaf "i32x4.mul"
  encodeWatSexp I32x4MinS_PlainInstr = Leaf "i32x4.min_s"
  encodeWatSexp I32x4MinU_PlainInstr = Leaf "i32x4.min_u"
  encodeWatSexp I32x4MaxS_PlainInstr = Leaf "i32x4.max_s"
  encodeWatSexp I32x4MaxU_PlainInstr = Leaf "i32x4.max_u"
  encodeWatSexp I32x4RelaxedLaneselect_PlainInstr = Leaf "i32x4.relaxed_laneselect"
  encodeWatSexp I32x4Shl_PlainInstr = Leaf "i32x4.shl"
  encodeWatSexp I32x4ShrS_PlainInstr = Leaf "i32x4.shr_s"
  encodeWatSexp I32x4ShrU_PlainInstr = Leaf "i32x4.shr_u"
  encodeWatSexp I32x4Bitmask_PlainInstr = Leaf "i32x4.bitmask"
  encodeWatSexp I64x2AllTrue_PlainInstr = Leaf "i64x2.all_true"
  encodeWatSexp I64x2Eq_PlainInstr = Leaf "i64x2.eq"
  encodeWatSexp I64x2Ne_PlainInstr = Leaf "i64x2.ne"
  encodeWatSexp I64x2LtS_PlainInstr = Leaf "i64x2.lt_s"
  encodeWatSexp I64x2GtS_PlainInstr = Leaf "i64x2.gt_s"
  encodeWatSexp I64x2LeS_PlainInstr = Leaf "i64x2.le_s"
  encodeWatSexp I64x2GeS_PlainInstr = Leaf "i64x2.ge_s"
  encodeWatSexp I64x2Abs_PlainInstr = Leaf "i64x2.abs"
  encodeWatSexp I64x2Neg_PlainInstr = Leaf "i64x2.neg"
  encodeWatSexp I64x2Add_PlainInstr = Leaf "i64x2.add"
  encodeWatSexp I64x2Sub_PlainInstr = Leaf "i64x2.sub"
  encodeWatSexp I64x2Mul_PlainInstr = Leaf "i64x2.mul"
  encodeWatSexp I64x2RelaxedLaneselect_PlainInstr = Leaf "i64x2.relaxed_laneselect"
  encodeWatSexp I64x2Shl_PlainInstr = Leaf "i64x2.shl"
  encodeWatSexp I64x2ShrS_PlainInstr = Leaf "i64x2.shr_s"
  encodeWatSexp I64x2ShrU_PlainInstr = Leaf "i64x2.shr_u"
  encodeWatSexp I64x2Bitmask_PlainInstr = Leaf "i64x2.bitmask"
  encodeWatSexp F32x4Eq_PlainInstr = Leaf "f32x4.eq"
  encodeWatSexp F32x4Ne_PlainInstr = Leaf "f32x4.ne"
  encodeWatSexp F32x4Lt_PlainInstr = Leaf "f32x4.lt"
  encodeWatSexp F32x4Gt_PlainInstr = Leaf "f32x4.gt"
  encodeWatSexp F32x4Le_PlainInstr = Leaf "f32x4.le"
  encodeWatSexp F32x4Ge_PlainInstr = Leaf "f32x4.ge"
  encodeWatSexp F32x4Abs_PlainInstr = Leaf "f32x4.abs"
  encodeWatSexp F32x4Neg_PlainInstr = Leaf "f32x4.neg"
  encodeWatSexp F32x4Sqrt_PlainInstr = Leaf "f32x4.sqrt"
  encodeWatSexp F32x4Ceil_PlainInstr = Leaf "f32x4.ceil"
  encodeWatSexp F32x4Floor_PlainInstr = Leaf "f32x4.floor"
  encodeWatSexp F32x4Trunc_PlainInstr = Leaf "f32x4.trunc"
  encodeWatSexp F32x4Nearest_PlainInstr = Leaf "f32x4.nearest"
  encodeWatSexp F32x4Add_PlainInstr = Leaf "f32x4.add"
  encodeWatSexp F32x4Sub_PlainInstr = Leaf "f32x4.sub"
  encodeWatSexp F32x4Mul_PlainInstr = Leaf "f32x4.mul"
  encodeWatSexp F32x4Div_PlainInstr = Leaf "f32x4.div"
  encodeWatSexp F32x4Min_PlainInstr = Leaf "f32x4.min"
  encodeWatSexp F32x4Max_PlainInstr = Leaf "f32x4.max"
  encodeWatSexp F32x4Pmin_PlainInstr = Leaf "f32x4.pmin"
  encodeWatSexp F32x4Pmax_PlainInstr = Leaf "f32x4.pmax"
  encodeWatSexp F32x4RelaxedMin_PlainInstr = Leaf "f32x4.relaxed_min"
  encodeWatSexp F32x4RelaxedMax_PlainInstr = Leaf "f32x4.relaxed_max"
  encodeWatSexp F32x4RelaxedMadd_PlainInstr = Leaf "f32x4.relaxed_madd"
  encodeWatSexp F32x4RelaxedNmadd_PlainInstr = Leaf "f32x4.relaxed_nmadd"
  encodeWatSexp F64x2Eq_PlainInstr = Leaf "f64x2.eq"
  encodeWatSexp F64x2Ne_PlainInstr = Leaf "f64x2.ne"
  encodeWatSexp F64x2Lt_PlainInstr = Leaf "f64x2.lt"
  encodeWatSexp F64x2Gt_PlainInstr = Leaf "f64x2.gt"
  encodeWatSexp F64x2Le_PlainInstr = Leaf "f64x2.le"
  encodeWatSexp F64x2Ge_PlainInstr = Leaf "f64x2.ge"
  encodeWatSexp F64x2Abs_PlainInstr = Leaf "f64x2.abs"
  encodeWatSexp F64x2Neg_PlainInstr = Leaf "f64x2.neg"
  encodeWatSexp F64x2Sqrt_PlainInstr = Leaf "f64x2.sqrt"
  encodeWatSexp F64x2Ceil_PlainInstr = Leaf "f64x2.ceil"
  encodeWatSexp F64x2Floor_PlainInstr = Leaf "f64x2.floor"
  encodeWatSexp F64x2Trunc_PlainInstr = Leaf "f64x2.trunc"
  encodeWatSexp F64x2Nearest_PlainInstr = Leaf "f64x2.nearest"
  encodeWatSexp F64x2Add_PlainInstr = Leaf "f64x2.add"
  encodeWatSexp F64x2Sub_PlainInstr = Leaf "f64x2.sub"
  encodeWatSexp F64x2Mul_PlainInstr = Leaf "f64x2.mul"
  encodeWatSexp F64x2Div_PlainInstr = Leaf "f64x2.div"
  encodeWatSexp F64x2Min_PlainInstr = Leaf "f64x2.min"
  encodeWatSexp F64x2Max_PlainInstr = Leaf "f64x2.max"
  encodeWatSexp F64x2Pmin_PlainInstr = Leaf "f64x2.pmin"
  encodeWatSexp F64x2Pmax_PlainInstr = Leaf "f64x2.pmax"
  encodeWatSexp F64x2RelaxedMin_PlainInstr = Leaf "f64x2.relaxed_min"
  encodeWatSexp F64x2RelaxedMax_PlainInstr = Leaf "f64x2.relaxed_max"
  encodeWatSexp F64x2RelaxedMadd_PlainInstr = Leaf "f64x2.relaxed_madd"
  encodeWatSexp F64x2RelaxedNmadd_PlainInstr = Leaf "f64x2.relaxed_nmadd"
  encodeWatSexp I16x8ExtendLowI8x16S_PlainInstr = Leaf "i16x8.extend_low_i8x16_s"
  encodeWatSexp I16x8ExtendLowI8x16U_PlainInstr = Leaf "i16x8.extend_low_i8x16_u"
  encodeWatSexp I16x8ExtendHighI8x16S_PlainInstr = Leaf "i16x8.extend_high_i8x16_s"
  encodeWatSexp I16x8ExtendHighI8x16U_PlainInstr = Leaf "i16x8.extend_high_i8x16_u"
  encodeWatSexp I32x4ExtendLowI16x8S_PlainInstr = Leaf "i32x4.extend_low_i16x8_s"
  encodeWatSexp I32x4ExtendLowI16x8U_PlainInstr = Leaf "i32x4.extend_low_i16x8_u"
  encodeWatSexp I32x4ExtendHighI16x8S_PlainInstr = Leaf "i32x4.extend_high_i16x8_s"
  encodeWatSexp I32x4ExtendHighI16x8U_PlainInstr = Leaf "i32x4.extend_high_i16x8_u"
  encodeWatSexp I32x4TruncSatF32x4S_PlainInstr = Leaf "i32x4.trunc_sat_f32x4_s"
  encodeWatSexp I32x4TruncSatF32x4U_PlainInstr = Leaf "i32x4.trunc_sat_f32x4_u"
  encodeWatSexp I32x4TruncSatF64x2SZero_PlainInstr = Leaf "i32x4.trunc_sat_f64x2_s_zero"
  encodeWatSexp I32x4TruncSatF64x2UZero_PlainInstr = Leaf "i32x4.trunc_sat_f64x2_u_zero"
  encodeWatSexp I32x4RelaxedTruncF32x4S_PlainInstr = Leaf "i32x4.relaxed_trunc_f32x4_s"
  encodeWatSexp I32x4RelaxedTruncF32x4U_PlainInstr = Leaf "i32x4.relaxed_trunc_f32x4_u"
  encodeWatSexp I32x4RelaxedTruncF64x2SZero_PlainInstr = Leaf "i32x4.relaxed_trunc_f64x2_s_zero"
  encodeWatSexp I32x4RelaxedTruncF64x2UZero_PlainInstr = Leaf "i32x4.relaxed_trunc_f64x2_u_zero"
  encodeWatSexp I64x2ExtendLowI32x4S_PlainInstr = Leaf "i64x2.extend_low_i32x4_s"
  encodeWatSexp I64x2ExtendLowI32x4U_PlainInstr = Leaf "i64x2.extend_low_i32x4_u"
  encodeWatSexp I64x2ExtendHighI32x4S_PlainInstr = Leaf "i64x2.extend_high_i32x4_s"
  encodeWatSexp I64x2ExtendHighI32x4U_PlainInstr = Leaf "i64x2.extend_high_i32x4_u"
  encodeWatSexp F32x4DemoteF64x2Zero_PlainInstr = Leaf "f32x4.demote_f64x2_zero"
  encodeWatSexp F32x4ConvertI32x4S_PlainInstr = Leaf "f32x4.convert_i32x4_s"
  encodeWatSexp F32x4ConvertI32x4U_PlainInstr = Leaf "f32x4.convert_i32x4_u"
  encodeWatSexp F64x2PromoteLowF32x4_PlainInstr = Leaf "f64x2.promote_low_f32x4"
  encodeWatSexp F64x2ConvertLowI32x4S_PlainInstr = Leaf "f64x2.convert_low_i32x4_s"
  encodeWatSexp F64x2ConvertLowI32x4U_PlainInstr = Leaf "f64x2.convert_low_i32x4_u"
  encodeWatSexp I16x8ExtaddPairwiseI8x16S_PlainInstr = Leaf "i16x8.extadd_pairwise_i8x16_s"
  encodeWatSexp I16x8ExtaddPairwiseI8x16U_PlainInstr = Leaf "i16x8.extadd_pairwise_i8x16_u"
  encodeWatSexp I16x8ExtmulLowI8x16S_PlainInstr = Leaf "i16x8.extmul_low_i8x16_s"
  encodeWatSexp I16x8ExtmulLowI8x16U_PlainInstr = Leaf "i16x8.extmul_low_i8x16_u"
  encodeWatSexp I16x8ExtmulHighI8x16S_PlainInstr = Leaf "i16x8.extmul_high_i8x16_s"
  encodeWatSexp I16x8ExtmulHighI8x16U_PlainInstr = Leaf "i16x8.extmul_high_i8x16_u"
  encodeWatSexp I16x8RelaxedDotI8x16I7x16S_PlainInstr = Leaf "i16x8.relaxed_dot_i8x16_i7x16_s"
  encodeWatSexp I32x4ExtaddPairwiseI16x8S_PlainInstr = Leaf "i32x4.extadd_pairwise_i16x8_s"
  encodeWatSexp I32x4ExtaddPairwiseI16x8U_PlainInstr = Leaf "i32x4.extadd_pairwise_i16x8_u"
  encodeWatSexp I32x4ExtmulLowI16x8S_PlainInstr = Leaf "i32x4.extmul_low_i16x8_s"
  encodeWatSexp I32x4ExtmulLowI16x8U_PlainInstr = Leaf "i32x4.extmul_low_i16x8_u"
  encodeWatSexp I32x4ExtmulHighI16x8S_PlainInstr = Leaf "i32x4.extmul_high_i16x8_s"
  encodeWatSexp I32x4ExtmulHighI16x8U_PlainInstr = Leaf "i32x4.extmul_high_i16x8_u"
  encodeWatSexp I32x4DotI16x8S_PlainInstr = Leaf "i32x4.dot_i16x8_s"
  encodeWatSexp I32x4RelaxedDotI8x16I7x16AddS_PlainInstr = Leaf "i32x4.relaxed_dot_i8x16_i7x16_add_s"
  encodeWatSexp I64x2ExtmulLowI32x4S_PlainInstr = Leaf "i64x2.extmul_low_i32x4_s"
  encodeWatSexp I64x2ExtmulLowI32x4U_PlainInstr = Leaf "i64x2.extmul_low_i32x4_u"
  encodeWatSexp I64x2ExtmulHighI32x4S_PlainInstr = Leaf "i64x2.extmul_high_i32x4_s"
  encodeWatSexp I64x2ExtmulHighI32x4U_PlainInstr = Leaf "i64x2.extmul_high_i32x4_u"

instance EncodeWatSexp Instr where
  encodeWatSexp (Plain_Instr p) = encodeWatSexp p
  encodeWatSexp (Block_Instr bi) = encodeWatSexp bi
  encodeWatSexp (Folded_Instr fi) = encodeWatSexp fi

instance EncodeWatSexpList Instrs where
  encodeWatSexpList = instrsSexpList

instance EncodeWatSexp FoldedInstr where
  encodeWatSexp (Plain_FoldedInstr p inputs) =
    let Node op kids = encodeWatSexp p
     in Node op (kids <> fmap encodeWatSexp inputs)
  encodeWatSexp (Block_FoldedInstr idM bt body) =
    Node "block" (encodeWatSexpList idM <> (blockTypeSexpList bt <> fmap encodeWatSexp body))
  encodeWatSexp (Loop_FoldedInstr idM bt body) =
    Node "loop" (encodeWatSexpList idM <> (blockTypeSexpList bt <> fmap encodeWatSexp body))
  encodeWatSexp (If_FoldedInstr idM bt inputs thenBody elseBody) =
    Node "if" (encodeWatSexpList idM <> (blockTypeSexpList bt <> fmap encodeWatSexp inputs <> [Node "then" (fmap encodeWatSexp thenBody)] <> [Node "else" (fmap encodeWatSexp elseBody) | not (null elseBody)]))
  encodeWatSexp (TryTable_FoldedInstr idM bt cs body) =
    Node "try_table" (encodeWatSexpList idM <> (blockTypeSexpList bt <> fmap encodeWatSexp cs <> fmap encodeWatSexp body))

instance EncodeWatSexpList Expr where
  encodeWatSexpList = exprSexpList

instance EncodeWatSexp Idx where
  encodeWatSexp (Index_Idx n) = encodeWatSexp n
  encodeWatSexp (Identifier_Idx i) = encodeWatSexp i

instance EncodeWatSexp TypeIdx where
  encodeWatSexp (TypeIdx i) = encodeWatSexp i

instance EncodeWatSexp FuncIdx where
  encodeWatSexp (FuncIdx i) = encodeWatSexp i

instance EncodeWatSexp GlobalIdx where
  encodeWatSexp (GlobalIdx i) = encodeWatSexp i

instance EncodeWatSexp TableIdx where
  encodeWatSexp (TableIdx i) = encodeWatSexp i

instance EncodeWatSexp MemIdx where
  encodeWatSexp (MemIdx i) = encodeWatSexp i

instance EncodeWatSexp TagIdx where
  encodeWatSexp (TagIdx i) = encodeWatSexp i

instance EncodeWatSexp ElemIdx where
  encodeWatSexp (ElemIdx i) = encodeWatSexp i

instance EncodeWatSexp DataIdx where
  encodeWatSexp (DataIdx i) = encodeWatSexp i

instance EncodeWatSexp LabelIdx where
  encodeWatSexp (LabelIdx i) = encodeWatSexp i

instance EncodeWatSexp LocalIdx where
  encodeWatSexp (LocalIdx i) = encodeWatSexp i

instance EncodeWatSexp FieldIdx where
  encodeWatSexp (FieldIdx i) = encodeWatSexp i

instance EncodeWatSexp Type where
  encodeWatSexp (Type rt) = encodeWatSexp rt

instance EncodeWatSexp Tag where
  encodeWatSexp (Tag idM tt) = Node "tag" (encodeWatSexpList idM <> [encodeWatSexp tt])

instance EncodeWatSexp Global where
  encodeWatSexp (Global idM gt e) = Node "global" (encodeWatSexpList idM <> [encodeWatSexp gt] <> encodeWatSexpList e)

instance EncodeWatSexp Mem where
  encodeWatSexp (Mem idM mt) = Node "memory" (encodeWatSexpList idM <> memTypeSexpList mt)

instance EncodeWatSexp Table where
  encodeWatSexp (Table idM tt e) = Node "table" (encodeWatSexpList idM <> (tableTypeSexpList tt <> encodeWatSexpList e))

instance EncodeWatSexp Local where
  encodeWatSexp (Local idM vt) = Node "local" (encodeWatSexpList idM <> [encodeWatSexp vt])

instance EncodeWatSexp Func where
  encodeWatSexp (Func idM tuM ls e) = Node "func" (encodeWatSexpList idM <> (encodeWatSexpList tuM <> fmap encodeWatSexp ls <> exprSexpList e))

instance EncodeWatSexpList DataMode where
  encodeWatSexpList = dataModeSexpList

instance EncodeWatSexp DataSegment where
  encodeWatSexp (DataSegment idM mode bs) = Node "data" (encodeWatSexpList idM <> (dataModeSexpList mode <> [encodeWatSexp bs]))

instance EncodeWatSexpList ElemMode where
  encodeWatSexpList = elemModeSexpList

instance EncodeWatSexp ElemExpr where
  encodeWatSexp (ElemExpr e) = Node "item" (encodeWatSexpList e)

instance EncodeWatSexpList ElemList where
  encodeWatSexpList = elemListSexpList

instance EncodeWatSexp ElemSegment where
  encodeWatSexp (ElemSegment idM mode el) = Node "elem" (encodeWatSexpList idM <> (elemModeSexpList mode <> elemListSexpList el))

instance EncodeWatSexp Start where
  encodeWatSexp (Start f) = Node "start" [encodeWatSexp f]

instance EncodeWatSexp Import where
  encodeWatSexp (Import nm1 nm2 et) = Node "import" [encodeWatSexp nm1, encodeWatSexp nm2, encodeWatSexp et]

instance EncodeWatSexp ExternIdx where
  encodeWatSexp (Tag_ExternIdx x) = Node "tag" [encodeWatSexp x]
  encodeWatSexp (Global_ExternIdx x) = Node "global" [encodeWatSexp x]
  encodeWatSexp (Memory_ExternIdx x) = Node "memory" [encodeWatSexp x]
  encodeWatSexp (Table_ExternIdx x) = Node "table" [encodeWatSexp x]
  encodeWatSexp (Func_ExternIdx x) = Node "func" [encodeWatSexp x]

instance EncodeWatSexp Export where
  encodeWatSexp (Export nm xx) = Node "export" [encodeWatSexp nm, encodeWatSexp xx]

instance EncodeWatSexp Decl where
  encodeWatSexp (Type_Decl t) = encodeWatSexp t
  encodeWatSexp (Import_Decl i) = encodeWatSexp i
  encodeWatSexp (Tag_Decl t) = encodeWatSexp t
  encodeWatSexp (Global_Decl g) = encodeWatSexp g
  encodeWatSexp (Mem_Decl m) = encodeWatSexp m
  encodeWatSexp (Table_Decl t) = encodeWatSexp t
  encodeWatSexp (Func_Decl f) = encodeWatSexp f
  encodeWatSexp (Data_Decl d) = encodeWatSexp d
  encodeWatSexp (Elem_Decl e) = encodeWatSexp e
  encodeWatSexp (Start_Decl s) = encodeWatSexp s
  encodeWatSexp (Export_Decl e) = encodeWatSexp e

instance EncodeWatSexp Module where
  encodeWatSexp (Module idM decls) = Node "module" (encodeWatSexpList idM <> fmap encodeWatSexp decls)
