{- HLINT ignore "Use camelCase" -}

-- | Embedding of the WebAssembly Text Format (WAT) from the WebAssembly Specification Release 3.0 (2026-07-07).
module Language.Wat where

import Data.ByteString (ByteString)
import Data.List (singleton)
import Data.Text (Text)
import Data.Text qualified as Text
import GHC.Generics (Generic)
import Numeric.Natural (Natural)
import Prettyprinter
import Prettyprinter.Util (reflow)

--------------------------------

class EncodeWat a where
  encodeWat :: a -> Doc ann

instance EncodeWat Text where
  encodeWat = reflow

--------------------------------

data Sexp = Node Text [Sexp]
  deriving (Generic, Eq, Show, Ord)

pattern Leaf :: Text -> Sexp
pattern Leaf t = Node t []

instance EncodeWat Sexp where
  encodeWat (Leaf t) = reflow t
  encodeWat (Node t es) = parens $ reflow t <+> (hcat . punctuate " " . fmap encodeWat) es

class EncodeWatSexp a where
  encodeWatSexp :: a -> Sexp

class EncodeWatSexpList a where
  encodeWatSexpList :: a -> [Sexp]

--------------------------------

-- # 6 WebAssembly Text Format (WAT)

-- ## 6.3 Values

-- ### 6.3.1 Integers

-- Use Haskell's `Integer`

-- ### 6.3.2 Floating Point

-- Use Haskell's `Float`

-- ### 6.3.3 Strings

-- Use Haskell's `ByteString`

-- ### 6.3.4 Names

-- | Names are strings denoting a literal character sequence.
data Name = Name Text
  deriving (Generic, Eq, Show, Ord)

-- ### 6.3.5 Identifiers

-- | Indices can be given in both numeric and symbolic form. Symbolic identifiers that stand in lieu of indices start with "$".
data Identifier = Identifier Text
  deriving (Generic, Eq, Show, Ord)

-- ## 6.4 Types

-- ### 6.4.1 Number Types

data NumType
  = I32_NumType
  | I64_NumType
  | F32_NumType
  | F64_NumType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.2 Vector Types

data VecType
  = V128_VecType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.3 Heap Types

data AbsHeapType
  = Any_AbsHeapType
  | Eq_AbsHeapType
  | I31_AbsHeapType
  | Struct_AbsHeapType
  | Array_AbsHeapType
  | None_AbsHeapType
  | Func_AbsHeapType
  | NoFunc_AbsHeapType
  | Exn_AbsHeapType
  | NoExn_AbsHeapType
  | Extern_AbsHeapType
  | NoExtern_AbsHeapType
  deriving (Generic, Eq, Show, Ord)

data HeapType
  = AbsHeapType_HeapType AbsHeapType
  | TypeIdx_HeapType TypeIdx
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.4 Reference Types

data Null = Null
  deriving (Generic, Eq, Show, Ord)

data RefType = RefType (Maybe Null) HeapType
  deriving (Generic, Eq, Show, Ord)

anyRefType :: RefType
anyRefType = RefType (Just Null) (AbsHeapType_HeapType Any_AbsHeapType)

eqRefType :: RefType
eqRefType = RefType (Just Null) (AbsHeapType_HeapType Eq_AbsHeapType)

i31RefType :: RefType
i31RefType = RefType (Just Null) (AbsHeapType_HeapType I31_AbsHeapType)

structRefType :: RefType
structRefType = RefType (Just Null) (AbsHeapType_HeapType Struct_AbsHeapType)

arrayRefType :: RefType
arrayRefType = RefType (Just Null) (AbsHeapType_HeapType Array_AbsHeapType)

noneRefType :: RefType
noneRefType = RefType (Just Null) (AbsHeapType_HeapType None_AbsHeapType)

funcRefType :: RefType
funcRefType = RefType (Just Null) (AbsHeapType_HeapType Func_AbsHeapType)

noFuncRefType :: RefType
noFuncRefType = RefType (Just Null) (AbsHeapType_HeapType NoFunc_AbsHeapType)

exnRefType :: RefType
exnRefType = RefType (Just Null) (AbsHeapType_HeapType Exn_AbsHeapType)

noExnRefType :: RefType
noExnRefType = RefType (Just Null) (AbsHeapType_HeapType NoExn_AbsHeapType)

externRefType :: RefType
externRefType = RefType (Just Null) (AbsHeapType_HeapType Extern_AbsHeapType)

noExternRefType :: RefType
noExternRefType = RefType (Just Null) (AbsHeapType_HeapType NoExtern_AbsHeapType)

-- ### 6.4.5 Value Types

data ValType
  = NumType_ValType NumType
  | VecType_ValType VecType
  | RefType_ValType RefType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.6 Composite Types

-- | Composite types are parsed into their respective abstract representation, paired with the local identifier context generated by their bound field or parameter identifiers.
data CompType
  = Struct_CompType [Field]
  | Array_CompType FieldType
  | Func_CompType [Param] [Result]
  deriving (Generic, Eq, Show, Ord)

-- | A field declaration with an optional identifier and field type.
data Field = Field (Maybe Identifier) FieldType
  deriving (Generic, Eq, Show, Ord)

-- | A parameter declaration with an optional identifier and value type.
data Param = Param (Maybe Identifier) ValType
  deriving (Generic, Eq, Show, Ord)

-- | A result declaration specifying a value type.
newtype Result = Result ValType
  deriving (Generic, Eq, Show, Ord)

-- | Field types can be mutable or immutable.
data FieldType = FieldType Bool StorageType
  deriving (Generic, Eq, Show, Ord)

-- | Storage types represent either value types or packed types.
data StorageType
  = ValType_StorageType ValType
  | PackType_StorageType PackType
  deriving (Generic, Eq, Show, Ord)

-- | Pack types represent i8 or i16 types.
data PackType
  = I8_PackType
  | I16_PackType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.7 Recursive Types

-- | Final types represent completed types.
data Final = Final
  deriving (Generic, Eq, Show, Ord)

-- | Sub types specify inheritance relationships and composite types.
data SubType = SubType (Maybe Final) [TypeIdx] CompType
  deriving (Generic, Eq, Show, Ord)

-- | Type definitions declare custom types with optional identifiers.
data TypeDef = TypeDef (Maybe Identifier) SubType
  deriving (Generic, Eq, Show, Ord)

-- | Recursive types are parsed into their respective abstract representation.
data RecType = RecType [TypeDef]
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.8 Address Types

-- | Address types are either i32 or i64.
data AddrType
  = I32_AddrType
  | I64_AddrType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.9 Limits

-- | Limits specify initial and optional maximum sizes.
data Limits = Limits Natural (Maybe Natural)
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.10 Tag Types

-- | Tag types specify the type signature of exception or event tags.
newtype TagType = TagType TypeUse
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.11 Global Types

-- | Global types specify the value type and mutability of a global variable.
data GlobalType = GlobalType Bool ValType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.12 Memory Types

-- | Memory types specify address types and size limits.
data MemType = MemType (Maybe AddrType) Limits
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.13 Table Types

-- | Table types specify address types, limits, and reference types.
data TableType = TableType (Maybe AddrType) Limits RefType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.14 External Types

-- | External types classify the kind of imports and exports.
data ExternalType
  = Tag_ExternalType (Maybe Identifier) TagType
  | Global_ExternalType (Maybe Identifier) GlobalType
  | Memory_ExternalType (Maybe Identifier) MemType
  | Table_ExternalType (Maybe Identifier) TableType
  | Func_ExternalType (Maybe Identifier) TypeUse
  deriving (Generic, Eq, Show, Ord)

-- ### 6.4.15 Type Uses

-- | Type uses reference type definitions, optionally inlining parameter and result declarations.
data TypeUse = TypeUse TypeIdx [Param] [Result]
  deriving (Generic, Eq, Show, Ord)

-- ## 6.5 Instructions

-- ### 6.5.1 Labels

-- | Structured control instructions can be annotated with an optional symbolic label identifier.
newtype Label = Label (Maybe Identifier)
  deriving (Generic, Eq, Show, Ord)

-- ### 6.5.2 to 6.5.10 Instructions

-- | Block types are either result types or references to type definitions.
data BlockType
  = Result_BlockType (Maybe Result)
  | TypeUse_BlockType TypeUse
  deriving (Generic, Eq, Show, Ord)

-- | Structured catch clauses for exception handling.
data Catch
  = Catch TagIdx LabelIdx
  | CatchRef TagIdx LabelIdx
  | CatchAll LabelIdx
  | CatchAllRef LabelIdx
  deriving (Generic, Eq, Show, Ord)

-- | Structured control instructions.
data BlockInstr
  = Block_BlockInstr (Maybe Identifier) BlockType [Instr] (Maybe Identifier)
  | Loop_BlockInstr (Maybe Identifier) BlockType [Instr] (Maybe Identifier)
  | If_BlockInstr (Maybe Identifier) BlockType [Instr] (Maybe Identifier) [Instr] (Maybe Identifier)
  | TryTable_BlockInstr (Maybe Identifier) BlockType [Catch] [Instr] (Maybe Identifier)
  deriving (Generic, Eq, Show, Ord)

-- | Memory instruction arguments (offset and alignment).
data MemArg = MemArg (Maybe Natural) (Maybe Natural)
  deriving (Generic, Eq, Show, Ord)

isMemArgEmpty :: MemArg -> Bool
isMemArgEmpty (MemArg Nothing Nothing) = True
isMemArgEmpty _ = False

-- | Lane index for SIMD instructions.
newtype LaneIdx = LaneIdx Natural
  deriving (Generic, Eq, Show, Ord)

-- | Plain instruction forms of WebAssembly.
data PlainInstr
  = -- ### 6.5.2 Parametric Instructions
    Unreachable_PlainInstr
  | Nop_PlainInstr
  | Drop_PlainInstr
  | Select_PlainInstr (Maybe [Result])
  | -- ### 6.5.3 Plain Control Instructions
    Br_PlainInstr LabelIdx
  | BrIf_PlainInstr LabelIdx
  | BrTable_PlainInstr [LabelIdx] LabelIdx
  | Return_PlainInstr
  | Call_PlainInstr FuncIdx
  | ReturnCall_PlainInstr FuncIdx
  | CallIndirect_PlainInstr TableIdx TypeUse
  | ReturnCallIndirect_PlainInstr TableIdx TypeUse
  | -- ### 6.5.4 Variable Instructions
    LocalGet_PlainInstr LocalIdx
  | LocalSet_PlainInstr LocalIdx
  | LocalTee_PlainInstr LocalIdx
  | GlobalGet_PlainInstr GlobalIdx
  | GlobalSet_PlainInstr GlobalIdx
  | -- ### 6.5.5 Table Instructions
    TableGet_PlainInstr TableIdx
  | TableSet_PlainInstr TableIdx
  | TableSize_PlainInstr TableIdx
  | TableGrow_PlainInstr TableIdx
  | TableFill_PlainInstr TableIdx
  | TableCopy_PlainInstr TableIdx TableIdx
  | TableInit_PlainInstr TableIdx ElemIdx
  | ElemDrop_PlainInstr ElemIdx
  | -- ### 6.5.6 Memory Instructions
    I32Load_PlainInstr MemIdx MemArg
  | I64Load_PlainInstr MemIdx MemArg
  | F32Load_PlainInstr MemIdx MemArg
  | F64Load_PlainInstr MemIdx MemArg
  | I32Load8S_PlainInstr MemIdx MemArg
  | I32Load8U_PlainInstr MemIdx MemArg
  | I32Load16S_PlainInstr MemIdx MemArg
  | I32Load16U_PlainInstr MemIdx MemArg
  | I64Load8S_PlainInstr MemIdx MemArg
  | I64Load8U_PlainInstr MemIdx MemArg
  | I64Load16S_PlainInstr MemIdx MemArg
  | I64Load16U_PlainInstr MemIdx MemArg
  | I64Load32S_PlainInstr MemIdx MemArg
  | I64Load32U_PlainInstr MemIdx MemArg
  | V128Load_PlainInstr MemIdx MemArg
  | V128Load8x8S_PlainInstr MemIdx MemArg
  | V128Load8x8U_PlainInstr MemIdx MemArg
  | V128Load16x4S_PlainInstr MemIdx MemArg
  | V128Load16x4U_PlainInstr MemIdx MemArg
  | V128Load32x2S_PlainInstr MemIdx MemArg
  | V128Load32x2U_PlainInstr MemIdx MemArg
  | V128Load8Splat_PlainInstr MemIdx MemArg
  | V128Load16Splat_PlainInstr MemIdx MemArg
  | V128Load32Splat_PlainInstr MemIdx MemArg
  | V128Load64Splat_PlainInstr MemIdx MemArg
  | V128Load32Zero_PlainInstr MemIdx MemArg
  | V128Load64Zero_PlainInstr MemIdx MemArg
  | V128Load8Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Load16Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Load32Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Load64Lane_PlainInstr MemIdx MemArg LaneIdx
  | I32Store_PlainInstr MemIdx MemArg
  | I64Store_PlainInstr MemIdx MemArg
  | F32Store_PlainInstr MemIdx MemArg
  | F64Store_PlainInstr MemIdx MemArg
  | I32Store8_PlainInstr MemIdx MemArg
  | I32Store16_PlainInstr MemIdx MemArg
  | I64Store8_PlainInstr MemIdx MemArg
  | I64Store16_PlainInstr MemIdx MemArg
  | I64Store32_PlainInstr MemIdx MemArg
  | V128Store_PlainInstr MemIdx MemArg
  | V128Store8Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Store16Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Store32Lane_PlainInstr MemIdx MemArg LaneIdx
  | V128Store64Lane_PlainInstr MemIdx MemArg LaneIdx
  | MemorySize_PlainInstr MemIdx
  | MemoryGrow_PlainInstr MemIdx
  | MemoryFill_PlainInstr MemIdx
  | MemoryCopy_PlainInstr MemIdx MemIdx
  | MemoryInit_PlainInstr MemIdx DataIdx
  | DataDrop_PlainInstr DataIdx
  | -- ### 6.5.7 Reference Instructions
    RefNull_PlainInstr HeapType
  | RefFunc_PlainInstr FuncIdx
  | RefIsNull_PlainInstr
  | RefAsNonNull_PlainInstr
  | RefEq_PlainInstr
  | RefTest_PlainInstr RefType
  | RefCast_PlainInstr RefType
  | -- ### 6.5.8 Aggregate Instructions
    RefI31_PlainInstr
  | I31GetS_PlainInstr
  | I31GetU_PlainInstr
  | StructNew_PlainInstr TypeIdx
  | StructNewDefault_PlainInstr TypeIdx
  | StructGet_PlainInstr TypeIdx FieldIdx
  | StructGetS_PlainInstr TypeIdx FieldIdx
  | StructGetU_PlainInstr TypeIdx FieldIdx
  | StructSet_PlainInstr TypeIdx FieldIdx
  | ArrayNew_PlainInstr TypeIdx
  | ArrayNewDefault_PlainInstr TypeIdx
  | ArrayNewFixed_PlainInstr TypeIdx Natural
  | ArrayNewData_PlainInstr TypeIdx DataIdx
  | ArrayNewElem_PlainInstr TypeIdx ElemIdx
  | ArrayGet_PlainInstr TypeIdx
  | ArrayGetS_PlainInstr TypeIdx
  | ArrayGetU_PlainInstr TypeIdx
  | ArraySet_PlainInstr TypeIdx
  | ArrayLen_PlainInstr
  | ArrayFill_PlainInstr TypeIdx
  | ArrayCopy_PlainInstr TypeIdx TypeIdx
  | ArrayInitData_PlainInstr TypeIdx DataIdx
  | ArrayInitElem_PlainInstr TypeIdx ElemIdx
  | AnyConvertExtern_PlainInstr
  | ExternConvertAny_PlainInstr
  | -- ### 6.5.9 Numeric Const Instructions
    I32Const_PlainInstr Integer
  | I64Const_PlainInstr Integer
  | F32Const_PlainInstr Float
  | F64Const_PlainInstr Float
  | -- ### 6.5.9 Numeric Operators
    -- i32 operators
    I32Eqz_PlainInstr
  | I32Eq_PlainInstr
  | I32Ne_PlainInstr
  | I32LtS_PlainInstr
  | I32LtU_PlainInstr
  | I32GtS_PlainInstr
  | I32GtU_PlainInstr
  | I32LeS_PlainInstr
  | I32LeU_PlainInstr
  | I32GeS_PlainInstr
  | I32GeU_PlainInstr
  | I32Clz_PlainInstr
  | I32Ctz_PlainInstr
  | I32Popcnt_PlainInstr
  | I32Extend8S_PlainInstr
  | I32Extend16S_PlainInstr
  | I32Add_PlainInstr
  | I32Sub_PlainInstr
  | I32Mul_PlainInstr
  | I32DivS_PlainInstr
  | I32DivU_PlainInstr
  | I32RemS_PlainInstr
  | I32RemU_PlainInstr
  | I32And_PlainInstr
  | I32Or_PlainInstr
  | I32Xor_PlainInstr
  | I32Shl_PlainInstr
  | I32ShrS_PlainInstr
  | I32ShrU_PlainInstr
  | I32Rotl_PlainInstr
  | I32Rotr_PlainInstr
  | -- i64 operators
    I64Eqz_PlainInstr
  | I64Eq_PlainInstr
  | I64Ne_PlainInstr
  | I64LtS_PlainInstr
  | I64LtU_PlainInstr
  | I64GtS_PlainInstr
  | I64GtU_PlainInstr
  | I64LeS_PlainInstr
  | I64LeU_PlainInstr
  | I64GeS_PlainInstr
  | I64GeU_PlainInstr
  | I64Clz_PlainInstr
  | I64Ctz_PlainInstr
  | I64Popcnt_PlainInstr
  | I64Extend8S_PlainInstr
  | I64Extend16S_PlainInstr
  | I64Extend32S_PlainInstr
  | I64Add_PlainInstr
  | I64Sub_PlainInstr
  | I64Mul_PlainInstr
  | I64DivS_PlainInstr
  | I64DivU_PlainInstr
  | I64RemS_PlainInstr
  | I64RemU_PlainInstr
  | I64And_PlainInstr
  | I64Or_PlainInstr
  | I64Xor_PlainInstr
  | I64Shl_PlainInstr
  | I64ShrS_PlainInstr
  | I64ShrU_PlainInstr
  | I64Rotl_PlainInstr
  | I64Rotr_PlainInstr
  | -- f32 operators
    F32Eq_PlainInstr
  | F32Ne_PlainInstr
  | F32Lt_PlainInstr
  | F32Gt_PlainInstr
  | F32Le_PlainInstr
  | F32Ge_PlainInstr
  | F32Abs_PlainInstr
  | F32Neg_PlainInstr
  | F32Sqrt_PlainInstr
  | F32Ceil_PlainInstr
  | F32Floor_PlainInstr
  | F32Trunc_PlainInstr
  | F32Nearest_PlainInstr
  | F32Add_PlainInstr
  | F32Sub_PlainInstr
  | F32Mul_PlainInstr
  | F32Div_PlainInstr
  | F32Min_PlainInstr
  | F32Max_PlainInstr
  | F32Copysign_PlainInstr
  | -- f64 operators
    F64Eq_PlainInstr
  | F64Ne_PlainInstr
  | F64Lt_PlainInstr
  | F64Gt_PlainInstr
  | F64Le_PlainInstr
  | F64Ge_PlainInstr
  | F64Abs_PlainInstr
  | F64Neg_PlainInstr
  | F64Sqrt_PlainInstr
  | F64Ceil_PlainInstr
  | F64Floor_PlainInstr
  | F64Trunc_PlainInstr
  | F64Nearest_PlainInstr
  | F64Add_PlainInstr
  | F64Sub_PlainInstr
  | F64Mul_PlainInstr
  | F64Div_PlainInstr
  | F64Min_PlainInstr
  | F64Max_PlainInstr
  | F64Copysign_PlainInstr
  | -- conversions
    I32WrapI64_PlainInstr
  | I32TruncF32S_PlainInstr
  | I32TruncF32U_PlainInstr
  | I32TruncF64S_PlainInstr
  | I32TruncF64U_PlainInstr
  | I32TruncSatF32S_PlainInstr
  | I32TruncSatF32U_PlainInstr
  | I32TruncSatF64S_PlainInstr
  | I32TruncSatF64U_PlainInstr
  | I64ExtendI32S_PlainInstr
  | I64ExtendI32U_PlainInstr
  | I64TruncF32S_PlainInstr
  | I64TruncF32U_PlainInstr
  | I64TruncF64S_PlainInstr
  | I64TruncF64U_PlainInstr
  | I64TruncSatF32S_PlainInstr
  | I64TruncSatF32U_PlainInstr
  | I64TruncSatF64S_PlainInstr
  | I64TruncSatF64U_PlainInstr
  | F32DemoteF64_PlainInstr
  | F32ConvertI32S_PlainInstr
  | F32ConvertI32U_PlainInstr
  | F32ConvertI64S_PlainInstr
  | F32ConvertI64U_PlainInstr
  | F64PromoteF32_PlainInstr
  | F64ConvertI32S_PlainInstr
  | F64ConvertI32U_PlainInstr
  | F64ConvertI64S_PlainInstr
  | F64ConvertI64U_PlainInstr
  | I32ReinterpretF32_PlainInstr
  | I64ReinterpretF64_PlainInstr
  | F32ReinterpretI32_PlainInstr
  | F64ReinterpretI64_PlainInstr
  | -- ### 6.5.10 Vector Instructions
    -- vector const and shuffle
    V128Const_PlainInstr Text [Integer]
  | I8x16Shuffle_PlainInstr [LaneIdx]
  | -- swizzle and splats
    I8x16Swizzle_PlainInstr
  | I8x16RelaxedSwizzle_PlainInstr
  | I8x16Splat_PlainInstr
  | I16x8Splat_PlainInstr
  | I32x4Splat_PlainInstr
  | I64x2Splat_PlainInstr
  | F32x4Splat_PlainInstr
  | F64x2Splat_PlainInstr
  | -- lanes
    I8x16ExtractLaneS_PlainInstr LaneIdx
  | I8x16ExtractLaneU_PlainInstr LaneIdx
  | I16x8ExtractLaneS_PlainInstr LaneIdx
  | I16x8ExtractLaneU_PlainInstr LaneIdx
  | I32x4ExtractLane_PlainInstr LaneIdx
  | I64x2ExtractLane_PlainInstr LaneIdx
  | F32x4ExtractLane_PlainInstr LaneIdx
  | F64x2ExtractLane_PlainInstr LaneIdx
  | I8x16ReplaceLane_PlainInstr LaneIdx
  | I16x8ReplaceLane_PlainInstr LaneIdx
  | I32x4ReplaceLane_PlainInstr LaneIdx
  | I64x2ReplaceLane_PlainInstr LaneIdx
  | F32x4ReplaceLane_PlainInstr LaneIdx
  | F64x2ReplaceLane_PlainInstr LaneIdx
  | -- vector ops
    V128AnyTrue_PlainInstr
  | V128Not_PlainInstr
  | V128And_PlainInstr
  | V128Andnot_PlainInstr
  | V128Or_PlainInstr
  | V128Xor_PlainInstr
  | V128Bitselect_PlainInstr
  | I8x16AllTrue_PlainInstr
  | I8x16Eq_PlainInstr
  | I8x16Ne_PlainInstr
  | I8x16LtS_PlainInstr
  | I8x16LtU_PlainInstr
  | I8x16GtS_PlainInstr
  | I8x16GtU_PlainInstr
  | I8x16LeS_PlainInstr
  | I8x16LeU_PlainInstr
  | I8x16GeS_PlainInstr
  | I8x16GeU_PlainInstr
  | I8x16Abs_PlainInstr
  | I8x16Neg_PlainInstr
  | I8x16Popcnt_PlainInstr
  | I8x16Add_PlainInstr
  | I8x16AddSatS_PlainInstr
  | I8x16AddSatU_PlainInstr
  | I8x16Sub_PlainInstr
  | I8x16SubSatS_PlainInstr
  | I8x16SubSatU_PlainInstr
  | I8x16MinS_PlainInstr
  | I8x16MinU_PlainInstr
  | I8x16MaxS_PlainInstr
  | I8x16MaxU_PlainInstr
  | I8x16AvgrU_PlainInstr
  | I8x16RelaxedLaneselect_PlainInstr
  | I8x16Shl_PlainInstr
  | I8x16ShrS_PlainInstr
  | I8x16ShrU_PlainInstr
  | I8x16Bitmask_PlainInstr
  | I8x16NarrowI16x8S_PlainInstr
  | I8x16NarrowI16x8U_PlainInstr
  | -- i16x8 ops
    I16x8AllTrue_PlainInstr
  | I16x8Eq_PlainInstr
  | I16x8Ne_PlainInstr
  | I16x8LtS_PlainInstr
  | I16x8LtU_PlainInstr
  | I16x8GtS_PlainInstr
  | I16x8GtU_PlainInstr
  | I16x8LeS_PlainInstr
  | I16x8LeU_PlainInstr
  | I16x8GeS_PlainInstr
  | I16x8GeU_PlainInstr
  | I16x8Abs_PlainInstr
  | I16x8Neg_PlainInstr
  | I16x8Add_PlainInstr
  | I16x8AddSatS_PlainInstr
  | I16x8AddSatU_PlainInstr
  | I16x8Sub_PlainInstr
  | I16x8SubSatS_PlainInstr
  | I16x8SubSatU_PlainInstr
  | I16x8Mul_PlainInstr
  | I16x8MinS_PlainInstr
  | I16x8MinU_PlainInstr
  | I16x8MaxS_PlainInstr
  | I16x8MaxU_PlainInstr
  | I16x8AvgrU_PlainInstr
  | I16x8Q15mulrSatS_PlainInstr
  | I16x8RelaxedQ15mulrS_PlainInstr
  | I16x8RelaxedLaneselect_PlainInstr
  | I16x8Shl_PlainInstr
  | I16x8ShrS_PlainInstr
  | I16x8ShrU_PlainInstr
  | I16x8Bitmask_PlainInstr
  | I16x8NarrowI32x4S_PlainInstr
  | I16x8NarrowI32x4U_PlainInstr
  | -- i32x4 ops
    I32x4AllTrue_PlainInstr
  | I32x4Eq_PlainInstr
  | I32x4Ne_PlainInstr
  | I32x4LtS_PlainInstr
  | I32x4LtU_PlainInstr
  | I32x4GtS_PlainInstr
  | I32x4GtU_PlainInstr
  | I32x4LeS_PlainInstr
  | I32x4LeU_PlainInstr
  | I32x4GeS_PlainInstr
  | I32x4GeU_PlainInstr
  | I32x4Abs_PlainInstr
  | I32x4Neg_PlainInstr
  | I32x4Add_PlainInstr
  | I32x4Sub_PlainInstr
  | I32x4Mul_PlainInstr
  | I32x4MinS_PlainInstr
  | I32x4MinU_PlainInstr
  | I32x4MaxS_PlainInstr
  | I32x4MaxU_PlainInstr
  | I32x4RelaxedLaneselect_PlainInstr
  | I32x4Shl_PlainInstr
  | I32x4ShrS_PlainInstr
  | I32x4ShrU_PlainInstr
  | I32x4Bitmask_PlainInstr
  | -- i64x2 ops
    I64x2AllTrue_PlainInstr
  | I64x2Eq_PlainInstr
  | I64x2Ne_PlainInstr
  | I64x2LtS_PlainInstr
  | I64x2GtS_PlainInstr
  | I64x2LeS_PlainInstr
  | I64x2GeS_PlainInstr
  | I64x2Abs_PlainInstr
  | I64x2Neg_PlainInstr
  | I64x2Add_PlainInstr
  | I64x2Sub_PlainInstr
  | I64x2Mul_PlainInstr
  | I64x2RelaxedLaneselect_PlainInstr
  | I64x2Shl_PlainInstr
  | I64x2ShrS_PlainInstr
  | I64x2ShrU_PlainInstr
  | I64x2Bitmask_PlainInstr
  | -- f32x4 ops
    F32x4Eq_PlainInstr
  | F32x4Ne_PlainInstr
  | F32x4Lt_PlainInstr
  | F32x4Gt_PlainInstr
  | F32x4Le_PlainInstr
  | F32x4Ge_PlainInstr
  | F32x4Abs_PlainInstr
  | F32x4Neg_PlainInstr
  | F32x4Sqrt_PlainInstr
  | F32x4Ceil_PlainInstr
  | F32x4Floor_PlainInstr
  | F32x4Trunc_PlainInstr
  | F32x4Nearest_PlainInstr
  | F32x4Add_PlainInstr
  | F32x4Sub_PlainInstr
  | F32x4Mul_PlainInstr
  | F32x4Div_PlainInstr
  | F32x4Min_PlainInstr
  | F32x4Max_PlainInstr
  | F32x4Pmin_PlainInstr
  | F32x4Pmax_PlainInstr
  | F32x4RelaxedMin_PlainInstr
  | F32x4RelaxedMax_PlainInstr
  | F32x4RelaxedMadd_PlainInstr
  | F32x4RelaxedNmadd_PlainInstr
  | -- f64x2 ops
    F64x2Eq_PlainInstr
  | F64x2Ne_PlainInstr
  | F64x2Lt_PlainInstr
  | F64x2Gt_PlainInstr
  | F64x2Le_PlainInstr
  | F64x2Ge_PlainInstr
  | F64x2Abs_PlainInstr
  | F64x2Neg_PlainInstr
  | F64x2Sqrt_PlainInstr
  | F64x2Ceil_PlainInstr
  | F64x2Floor_PlainInstr
  | F64x2Trunc_PlainInstr
  | F64x2Nearest_PlainInstr
  | F64x2Add_PlainInstr
  | F64x2Sub_PlainInstr
  | F64x2Mul_PlainInstr
  | F64x2Div_PlainInstr
  | F64x2Min_PlainInstr
  | F64x2Max_PlainInstr
  | F64x2Pmin_PlainInstr
  | F64x2Pmax_PlainInstr
  | F64x2RelaxedMin_PlainInstr
  | F64x2RelaxedMax_PlainInstr
  | F64x2RelaxedMadd_PlainInstr
  | F64x2RelaxedNmadd_PlainInstr
  | -- extension vectors (page 26)
    I16x8ExtendLowI8x16S_PlainInstr
  | I16x8ExtendLowI8x16U_PlainInstr
  | I16x8ExtendHighI8x16S_PlainInstr
  | I16x8ExtendHighI8x16U_PlainInstr
  | I32x4ExtendLowI16x8S_PlainInstr
  | I32x4ExtendLowI16x8U_PlainInstr
  | I32x4ExtendHighI16x8S_PlainInstr
  | I32x4ExtendHighI16x8U_PlainInstr
  | I32x4TruncSatF32x4S_PlainInstr
  | I32x4TruncSatF32x4U_PlainInstr
  | I32x4TruncSatF64x2SZero_PlainInstr
  | I32x4TruncSatF64x2UZero_PlainInstr
  | I32x4RelaxedTruncF32x4S_PlainInstr
  | I32x4RelaxedTruncF32x4U_PlainInstr
  | I32x4RelaxedTruncF64x2SZero_PlainInstr
  | I32x4RelaxedTruncF64x2UZero_PlainInstr
  | I64x2ExtendLowI32x4S_PlainInstr
  | I64x2ExtendLowI32x4U_PlainInstr
  | I64x2ExtendHighI32x4S_PlainInstr
  | I64x2ExtendHighI32x4U_PlainInstr
  | F32x4DemoteF64x2Zero_PlainInstr
  | F32x4ConvertI32x4S_PlainInstr
  | F32x4ConvertI32x4U_PlainInstr
  | F64x2PromoteLowF32x4_PlainInstr
  | F64x2ConvertLowI32x4S_PlainInstr
  | F64x2ConvertLowI32x4U_PlainInstr
  | -- pairwise and dot products (page 26)
    I16x8ExtaddPairwiseI8x16S_PlainInstr
  | I16x8ExtaddPairwiseI8x16U_PlainInstr
  | I16x8ExtmulLowI8x16S_PlainInstr
  | I16x8ExtmulLowI8x16U_PlainInstr
  | I16x8ExtmulHighI8x16S_PlainInstr
  | I16x8ExtmulHighI8x16U_PlainInstr
  | I16x8RelaxedDotI8x16I7x16S_PlainInstr
  | I32x4ExtaddPairwiseI16x8S_PlainInstr
  | I32x4ExtaddPairwiseI16x8U_PlainInstr
  | I32x4ExtmulLowI16x8S_PlainInstr
  | I32x4ExtmulLowI16x8U_PlainInstr
  | I32x4ExtmulHighI16x8S_PlainInstr
  | I32x4ExtmulHighI16x8U_PlainInstr
  | I32x4DotI16x8S_PlainInstr
  | I32x4RelaxedDotI8x16I7x16AddS_PlainInstr
  | I64x2ExtmulLowI32x4S_PlainInstr
  | I64x2ExtmulLowI32x4U_PlainInstr
  | I64x2ExtmulHighI32x4S_PlainInstr
  | I64x2ExtmulHighI32x4U_PlainInstr
  deriving (Generic, Eq, Show, Ord)

-- encMem :: Doc ann -> MemIdx -> MemArg -> Doc ann
-- encMem op m arg =
--   if isMemArgEmpty arg
--     then op <+> encodeWat m
--     else op <+> encodeWat m <+> encodeWat arg

-- encMemLane :: Doc ann -> MemIdx -> MemArg -> LaneIdx -> Doc ann
-- encMemLane op m arg lane =
--   if isMemArgEmpty arg
--     then op <+> encodeWat m <+> encodeWat lane
--     else op <+> encodeWat m <+> encodeWat arg <+> encodeWat lane

-- | General WebAssembly instructions.
data Instr
  = Plain_Instr PlainInstr
  | Block_Instr BlockInstr
  | Folded_Instr FoldedInstr
  deriving (Generic, Eq, Show, Ord)

-- | Sequences of instructions.
newtype Instrs = Instrs [Instr]
  deriving (Generic, Eq, Show, Ord)

-- ### 6.5.11 Folded Instructions

-- | Folded instructions are syntactic sugar to group instructions visually.
data FoldedInstr
  = Plain_FoldedInstr PlainInstr [FoldedInstr]
  | Block_FoldedInstr (Maybe Identifier) BlockType [Instr]
  | Loop_FoldedInstr (Maybe Identifier) BlockType [Instr]
  | If_FoldedInstr (Maybe Identifier) BlockType [FoldedInstr] [Instr] [Instr]
  | TryTable_FoldedInstr (Maybe Identifier) BlockType [Catch] [Instr]
  deriving (Generic, Eq, Show, Ord)

-- ### Expressions

-- | Expressions are written as instruction sequences.
newtype Expr = Expr [Instr]
  deriving (Generic, Eq, Show, Ord)

-- ## 6.6 Modules

-- ### 6.6.1 Indices

-- | Indices can be given in either numeric or symbolic form.
data Idx
  = Index_Idx Natural
  | Identifier_Idx Identifier
  deriving (Generic, Eq, Show, Ord)

data TypeIdx = TypeIdx Idx
  deriving (Generic, Eq, Show, Ord)

data FuncIdx = FuncIdx Idx
  deriving (Generic, Eq, Show, Ord)

data GlobalIdx = GlobalIdx Idx
  deriving (Generic, Eq, Show, Ord)

data TableIdx = TableIdx Idx
  deriving (Generic, Eq, Show, Ord)

data MemIdx = MemIdx Idx
  deriving (Generic, Eq, Show, Ord)

data TagIdx = TagIdx Idx
  deriving (Generic, Eq, Show, Ord)

data ElemIdx = ElemIdx Idx
  deriving (Generic, Eq, Show, Ord)

data DataIdx = DataIdx Idx
  deriving (Generic, Eq, Show, Ord)

data LabelIdx = LabelIdx Idx
  deriving (Generic, Eq, Show, Ord)

data LocalIdx = LocalIdx Idx
  deriving (Generic, Eq, Show, Ord)

data FieldIdx = FieldIdx Idx
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.2 Types

-- | A type definition consists of a recursive type.
newtype Type = Type RecType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.3 Tags

-- | Tag definitions bind a symbolic tag identifier.
data Tag = Tag (Maybe Identifier) TagType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.4 Globals

-- | Global definitions bind a symbolic global identifier.
data Global = Global (Maybe Identifier) GlobalType Expr
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.5 Memories

-- | Memory definitions bind a symbolic memory identifier.
data Mem = Mem (Maybe Identifier) MemType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.6 Tables

-- | Table definitions bind a symbolic table identifier.
data Table = Table (Maybe Identifier) TableType Expr
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.7 Functions

-- | Local variables in a function.
data Local = Local (Maybe Identifier) ValType
  deriving (Generic, Eq, Show, Ord)

-- | Function definitions bind a symbolic function identifier and local identifiers for its parameters and locals.
data Func = Func (Maybe Identifier) (Maybe TypeUse) [Local] Expr
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.8 Data Segments

-- | Data segments can be active or passive.
data DataMode
  = Passive_DataMode
  | Active_DataMode MemIdx Expr
  deriving (Generic, Eq, Show, Ord)

-- | Data segments allow for an optional memory index to identify the memory to initialize.
data DataSegment = DataSegment (Maybe Identifier) DataMode ByteString
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.9 Element Segments

-- | Element segment initialization mode.
data ElemMode
  = Passive_ElemMode
  | Active_ElemMode TableIdx Expr
  | Declare_ElemMode
  deriving (Generic, Eq, Show, Ord)

-- | Individual element expressions.
newtype ElemExpr = ElemExpr Expr
  deriving (Generic, Eq, Show, Ord)

-- | A list of elements with reference type.
data ElemList = ElemList RefType [ElemExpr]
  deriving (Generic, Eq, Show, Ord)

-- | Element segments allow for an optional table index to identify the table to initialize.
data ElemSegment = ElemSegment (Maybe Identifier) ElemMode ElemList
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.10 Start Functions

-- | A start function is defined in terms of its index.
newtype Start = Start FuncIdx
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.11 Imports

-- | Imports define the external module, name, and type category.
data Import = Import Name Name ExternalType
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.12 Exports

-- | Export category and target index.
data ExternIdx
  = Tag_ExternIdx TagIdx
  | Global_ExternIdx GlobalIdx
  | Memory_ExternIdx MemIdx
  | Table_ExternIdx TableIdx
  | Func_ExternIdx FuncIdx
  deriving (Generic, Eq, Show, Ord)

-- | Exports reveal definitions to the outside environment.
data Export = Export Name ExternIdx
  deriving (Generic, Eq, Show, Ord)

-- ### 6.6.13 Modules

-- | Module declarations.
data Decl
  = Type_Decl Type
  | Import_Decl Import
  | Tag_Decl Tag
  | Global_Decl Global
  | Mem_Decl Mem
  | Table_Decl Table
  | Func_Decl Func
  | Data_Decl DataSegment
  | Elem_Decl ElemSegment
  | Start_Decl Start
  | Export_Decl Export
  deriving (Generic, Eq, Show, Ord)

-- | A module consists of a sequence of declarations.
data Module = Module (Maybe Identifier) [Decl]
  deriving (Generic, Eq, Show, Ord)
